In [1]:
import pandas as pd

In [196]:
pd.set_option('max_columns', 50)
pd.set_option('max_row', 100)

excel = pd.ExcelFile('osaka_car.xls')
osaka_sheet = excel.sheet_names
df = pd.read_excel('osaka_car.xls', osaka_sheet)

In [197]:
osa_car1 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 31, 33, 34, 37, 40, 41, 43, 44]
osa_car2 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]
print(len(osa_car1)) # 以降 エクセルのコラム数　47
print(len(osa_car2)) # H23以前　エクセルのコラム数　46

21
19

In [233]:
len(df['H14'].columns)

46

In [251]:
df14 = df['H14']
df14_1 = df14.iloc[10:40,  [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]]
df14_1.iloc[0, 0].replace('平成', '')
df14_1.iloc[0, 0].replace('　', '')

'平成９'

In [247]:
df14_1.columns = [i for i in range(len(df14_1.columns))]
df14_1 = df14_1.iloc[:5, :]
df14_1 = df14_1.T.dropna()
df14_1 = df14_1.T
len(df14_1.columns)

17

In [236]:
df14_1

,Unnamed: 1,Unnamed: 2,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 11,Unnamed: 14,Unnamed: 17,Unnamed: 20,Unnamed: 23,Unnamed: 25,Unnamed: 28,Unnamed: 30,Unnamed: 34,Unnamed: 37,Unnamed: 39,Unnamed: 40,Unnamed: 42,Unnamed: 43
10,平成９,NaN,945839,-2591.0,549522,186374,363148,180320,43376,132292,4652,2835,18416,NaN,NaN,160238,-90.0,8291,-2501.0
11,NaN,10,931917,-2633.0,548197,195662,352535,169856,41913,123384,4559,2740,19033,NaN,NaN,157838,-91.0,8240,-2542.0
12,NaN,11,921544,-2748.0,543083,203759,339324,163018,39669,118858,4491,2683,19295,NaN,NaN,159341,-95.0,8259,-2653.0
13,NaN,12,917210,-2789.0,539770,210901,328869,158380,39142,114631,4607,2637,19560,NaN,NaN,162574,-101.0,8194,-2688.0
14,NaN,13,913052,-2753.0,537677,216334,321343,153369,38250,110497,4622,2479,19813,NaN,NaN,165220,-88.0,8063,-2665.0
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,１,北,44823,-94.0,25122,9760,15362,10609,1425,9108,76,191,652,NaN,NaN,6883,-6.0,348,-88.0
17,２,都島,26880,-59.0,17110,7231,9879,3837,867,2967,3,21,432,NaN,NaN,4524,-2.0,147,-57.0
18,３,福島,23340,-923.0,11532,4831,6701,5203,1264,3901,38,34,556,NaN,NaN,3877,-1.0,1604,-922.0
19,４,此花,24428,-6.0,12802,5190,7612,5088,2231,2611,246,207,1181,NaN,NaN,4190,-3.0,132,-3.0
20,５,中央,44942,-81.0,27170,10228,16942,9658,677,8969,12,50,651,NaN,NaN,6061,-2.0,210,-79.0
21,６,西,35746,-138.0,18930,7658,11272,9584,1578,7679,327,34,560,NaN,NaN,5312,-11.0,459,-127.0
22,７,港,29765,-77.0,15141,6266,8875,6033,2129,3303,601,326,967,NaN,NaN,5330,-1.0,288,-76.0
23,８,大正,29222,-26.0,15175,6053,9122,6424,2773,3116,535,112,797,NaN,NaN,5606,-1.0,202,-25.0
24,９,天王寺,18957,-50.0,11792,5348,6444,2993,327,2666,-,18,173,NaN,NaN,3338,-3.0,133,-47.0
25,10,浪速,21714,-43.0,10562,4608,5954,4866,964,3887,15,13,832,NaN,NaN,4565,-1.0,267,-42.0
26,11,西淀川,38077,-76.0,20938,8478,12460,8211,3329,4691,191,117,1279,NaN,NaN,5954,-3.0,386,-73.0
27,12,淀川,57294,-71.0,36019,13572,22447,9427,1419,7957,51,81,815,NaN,NaN,9184,-2.0,258,-69.0
28,13,東淀川,55004,-75.0,34642,13473,21169,6478,1687,4776,15,213,1177,NaN,NaN,10287,-3.0,181,-72.0
29,14,東成,26229,-106.0,15031,6228,8803,4607,979,3596,32,113,446,NaN,NaN,5015,-3.0,382,-103.0
30,15,生野,44144,-119.0,25588,10253,15335,6024,1215,4805,4,65,690,NaN,NaN,10170,-2.0,560,-117.0
31,16,旭,26961,-24.0,17261,6895,10366,2952,574,2372,6,36,358,NaN,NaN,5397,-2.0,93,-22.0
32,17,城東,48170,-79.0,30155,11714,18441,6147,1369,4746,32,126,1240,NaN,NaN,8465,-1.0,324,-78.0
33,18,鶴見,38387,-73.0,23286,9416,13870,6241,2550,3652,39,76,836,NaN,NaN,6666,-1.0,286,-72.0
34,19,阿倍野,25624,-9.0,17570,7907,9663,2424,359,2063,2,25,305,NaN,NaN,4475,-1.0,84,-8.0
35,20,住之江,52609,-148.0,29176,11355,17821,10770,4093,4450,2227,197,2119,NaN,NaN,8227,-4.0,319,-144.0
36,21,住吉,45345,-8.0,30245,12465,17780,3996,724,3254,18,144,506,NaN,NaN,8838,-1.0,83,-7.0
37,22,東住吉,46972,-313.0,28058,11594,16464,6331,1502,4803,26,24,1026,NaN,NaN,9716,-4.0,614,-309.0
38,23,平野,77165,-106.0,47112,18947,28165,10188,2521,7630,37,178,1323,NaN,NaN,16355,-1.0,506,-105.0
39,24,西成,31254,-49.0,17260,6864,10396,5278,1694,3495,89,78,892,NaN,NaN,6785,-29.0,197,-20.0

In [264]:
# 年度のエクセルファイルを必要部分を切り出す
def seikei(df):
    df = df.copy()
    osa_car1 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 31, 33, 34, 37, 40, 41, 43, 44]
    osa_car2 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 31, 32, 33, 36, 39, 40, 42, 43]
    osa_car3 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]
    osa_car4 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 34, 37, 39, 40, 42, 43]
    osa_car5 = [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]
    if len(df.columns) == 47:
        df1 = df.iloc[10:40, osa_car1]
        df2 = df1.iloc[:5, :]
        df2 = df2.T.dropna()
        df2 = df2.T
        if len(df2.columns) != 20:
            df1 = df.iloc[10:40, osa_car2]
    elif len(df.columns) == 46:
        df1 = df.iloc[10: 40, osa_car3]
        df2 = df1.iloc[:5, :]
        df2 = df2.T.dropna()
        df2 = df2.T
        if len(df2.columns) < 18:
            df1 = df.iloc[10:40, osa_car4]
    else:
        pass
    print(df1)
    return pd.DataFrame(df1)

def bunri(df):
    df_all = df.iloc[:5, :]
    df_area = df.iloc[6:, :]
    return pd.DataFrame(df_all), pd.DataFrame(df_area)

def remove_n_replace(df, column_name1, column_name2):
    df.iloc[0, 0] = df.iloc[0, 0].replace('平　成　', '')
    df.iloc[0, 0] = df.iloc[0, 0].replace('平 成  ', '')
    df.iloc[0, 0] = df.iloc[0, 0].replace('平 成　', '')
    df.iloc[0, 0] = df.iloc[0, 0].replace('平成', '')
    df = df.T.dropna()
    df = df.T
    if len(df.columns) == 20:
        problem_col= [2, 17, 19]
        df.columns = column_name1
        for i in range(len(df)):
            for i2 in problem_col:
                df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
                df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
                df.iloc[i, i2] = int(df.iloc[i, i2].replace(',', ''))
                if df.iloc[i, i2] < 0:
                    df.iloc[i, i2] = df.iloc[i, i2] * -1
        
        df['特種用途車'] = df['普通特種'] + df['小型特種']
        df = df.drop(['特種特殊総数', '普通特種', '小型特種'], axis=1)
        return df
    
    elif len(df.columns) == 18:
        problem_col = [2, 15, 17]
        df.columns = column_name2
        for i in range(len(df)):
            for i2 in problem_col:
                df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
                df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
                df.iloc[i, i2] = int(df.iloc[i, i2].replace(',', ''))
                if df.iloc[i, i2] < 0:
                    df.iloc[i, i2] = df.iloc[i, i2] * -1
        return df
    else:
        print(len(df.columns))

# 平成を西暦に(データフレーム用)
def heiseireki(df):
    print(df)
    for i in range(len(df)):
        if len(str(df.iloc[i, 0])) == 2:
            df.iloc[i, 0] = int(df.iloc[i, 0]) + 1988
        else:
            print(df.iloc[i, 0])
    return df

# 平成を西暦に（単独用）
def heiseireki_alone(year):
    year = int(year.replace('H', ''))
    year = year + 1988
    return year

def remove_area(df, column_name1, column_name2):
    df = df.iloc[:, 1:].copy()
    if len(df.columns) == 20:
        problem_col=[2, 17, 19]
        df.columns = column_name1
        for i in range(len(df)):
            for i2 in problem_col:
                df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
                df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
                try:
                    df.iloc[i, i2] = int(df.iloc[i, i2].replace(',', ''))
                except:
                    df.iloc[i, i2] = 0
                    
                if df.iloc[i, i2] < 0:
                    df.iloc[i, i2] = df.iloc[i, i2] * -1
                elif df.iloc[i, i2] == 'NaN':
                    df.iloc[i, i2] = 0
                else:
                    pass
                
        df['特種用途車'] = df['普通特種'] + df['小型特種']
        df = df.drop(['特種特殊総数', '普通特種', '小型特種'], axis=1)
        return df
    
    elif len(df.columns) == 18:
        problem_col=[2, 15, 17]
        df.columns = column_name2
        for i in range(len(df)):
            for i2 in problem_col:
                df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
                df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
                try:
                    df.iloc[i, i2] = int(df.iloc[i, i2].replace(',', ''))
                except:
                    df.iloc[i, i2] = 0
                    
                if df.iloc[i, i2] < 0:
                    df.iloc[i, i2] = df.iloc[i, i2] * -1
                elif df.iloc[i, i2] == 'NaN':
                    df.iloc[i, i2] = 0
                else:
                    pass
        return df
    
def area_betsu(df, year, column_name1, column_name2):
    df = remove_area(df, column_name1, column_name2)
    df['年度'] = year
    df.index = [i for i in range(len(df))]
    return df

In [265]:
def make_data(df):
    dfa = pd.DataFrame()
    dfar = pd.DataFrame()
    osa_carA=  ['総数', '電気自動車総数', '乗用車総数', '普通乗用車', '小型乗用車', '貨物車総数', '貨物普通車', '貨物小型車', '貨物被牽引車',
            'バス', '特種特殊総数', '普通特種', '小型特種', '大型特種', '小型二輪', '軽自動車', '電気軽自動車', '小型特殊自動車', '電気小型特殊自動車']
    osa_carB = ['総数', '電気自動車総数', '乗用車総数', '普通乗用車', '小型乗用車', '貨物車総数', '貨物普通車', '貨物小型車', '貨物被牽引車',
            'バス', '特種用途車', '大型特種', '小型二輪', '軽自動車', '電気軽自動車', '小型特殊自動車', '電気小型特殊自動車']
    
    osa_carA1 = osa_carA.copy()
    osa_carA2 = osa_carA.copy()
    osa_carA1.insert(0, '年度')
    osa_carA2.insert(0, '地域')
    osa_carB1 = osa_carB.copy()
    osa_carB2 = osa_carB.copy()
    osa_carB1.insert(0, '年度')
    osa_carB2.insert(0, '地域')
    
    for i in df.keys():
        print(i)
        year1 = heiseireki_alone(i)
        df1 = seikei(df[i])
        df_all, df_area = bunri(df1)
        df_all = remove_n_replace(df_all, osa_carA1, osa_carB1)
        df_all = heiseireki(df_all)
        df_area = area_betsu(df_area, year1, osa_carA2, osa_carB2)
        
        dfa = pd.concat([dfa, df_all], axis=1, join='inner')
        dfar = pd.concat([dfar, df_area], axis=1, join='inner')
    return dfa, dfar

In [266]:
df_all, df_area = make_data(df)

H29
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平　成　24        NaN     835576    (3,110)     478560      230215
11         25        NaN     838591    (3,146)     477502      234207
12         26        NaN     842716    (3,268)     475085      235892
13         27        NaN     841066       3341     475260      239448
14         28        NaN     845427       3366     477819      244678
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      42041        131      25769       13478
17          ２         都島      25014         49      15726        8594
18          ３         福島      21739        884      11638        6520
19          ４         此花      25009        112      11613        5920
20          ５         中央      45607         63      29768       14784
21          ６          西      34527        178      20344       10592
22          ７          港      27679        119      13021        6815
23          ８         大正      26463         60      11986        5955
24          ９        天王寺      17583         46      11621        7338
25         10         浪速      19567         77      10092        5385
26         11        西淀川      38552        131      19817       10088
27         12         淀川      55105        100      34104       15897
28         13        東淀川      46598         75      26809       13057
29         14         東成      23461        115      13129        6764
30         15         生野      37594        165      20310       10235
31         16          旭      23760         24      14133        7120
32         17         城東      44327        102      26789       13784
33         18         鶴見      37771         86      21306       11062
34         19        阿倍野      24593         13      16900        9707
35         20        住之江      52794        280      24500       11878
36         21         住吉      39321         22      24442       12409
37         22        東住吉      41019        285      23215       11901
38         23         平野      69983        213      37928       18875
39         24         西成      25320         35      12859        6520

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      248345      110288       30128       74634        5526        2070
11      243295      109766       30440       73678        5648        1998
12      239193      109121       30950       72530        5641        1994
13      235812      108659       31281       71610        5768        2072
14      233141      108409       31530       70967        5912        2146
15         NaN         NaN         NaN         NaN         NaN         NaN
16       12291        6233         842        5378          13         220
17        7132        2339         584        1752           3          30
18        5118        2984         713        2236          35          14
19        5693        4821        2207        2115         499         305
20       14984        6361         398        5951          12          42
21        9752        6132         921        5068         143          16
22        6206        5324        2296        2411         617         207
23        6031        5476        2504        2528         444         171
24        4283        1518         176        1338           4          15
25        4707        3074         687        2376          11          26
26        9729        6918        2923        3794         201         102
27       18207        6591        1034        5547          10          89
28       13752        3878        1047        2829           2         129
29        6365        2976         730        2226          20          12
30       10075        3732         821        2907           4          75
31        7013        1720         347        1362          11          38
32       13005        3834         956        2863          15          30
33       10244        4174        1790        2359          25          31
34        7193        1238         186        1051           1          16
35       12622       12435        5498        3279        3658         269
36       12033        2286         510        1759          17         133
37       11314        3667         961        2657          49          64
38       19053        7244        2103        5067          74          68
39        6339        3454        1296        2114          44          44

   Unnamed: 30 Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40  \
10       20682       12865        2522        5295       22742      194300
11       20950       13148        2494        5308       22837      198708
12       21248       13394        2555        5299       22188      206212
13       21660       13742        2628        5290       22822      203718
14       22025       14102        2653        5270       22805      205382
15         NaN         NaN         NaN         NaN         NaN         NaN
16         650         373         121         156         999        7920
17         365         204          92          69         831        5641
18         519         319         118          82         537        4587
19        1679        1326          53         300         697        5652
20         509         239          91         179        1020        7789
21         673         355          71         247         799        6194
22        1718         853          46         819         691        6414
23        1131         705          56         370         622        6822
24         201         117          53          31         427        3696
25         920         394         343         183         515        4743
26        1700        1224          81         395         989        8658
27         521         405          77          39        1699       11910
28         970         700          74         196        1679       13023
29         397         219         123          55         657        6025
30         699         509          96          94         931       11399
31         451         347          50          54         812        6549
32         893         543         133         217        1536       11023
33         797         513         128         156        1055       10146
34         242         178          45          19         739        5413
35        3142        2147         153         842        1046       11034
36         790         277          71         442        1098       10516
37         956         588         254         114        1094       11606
38        1343        1052         181         110        1679       21235
39         759         515         143         101         653        7387

   Unnamed: 41 Unnamed: 43 Unnamed: 44
10       (200)        6934     (2,910)
11       (209)        6830     (2,937)
12       (222)        6868     (3,046)
13       (215)        6875     (3,126)
14        -206        6841       -3160
15         NaN         NaN         NaN
16          20         250         111
17           3          82          47
18           4        1460         880
19           5         242         107
20          11         118          52
21          28         369         150
22           7         304         112
23           4         255          56
24           2         105          44
25          10         197          67
26          16         368         115
27          10         191          90
28           8         110          67
29           4         265         111
30           4         448         161
31           6          57          18
32           3         222          99
33           9         262          77
34           7          45           6
35          17         368         263
36           6          56          16
37           9         417         276
38          10         486         203
39           3         164          32
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  24  835576    3110  478560  230215  248345  110288  30128  74634   5526
11  25  838591    3146  477502  234207  243295  109766  30440  73678   5648
12  26  842716    3268  475085  235892  239193  109121  30950  72530   5641
13  27  841066    3341  475260  239448  235812  108659  31281  71610   5768
14  28  845427    3366  477819  244678  233141  108409  31530  70967   5912

      バス  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車  特種用途車
10  2070  5295  22742  194300    200    6934      2910  15387
11  1998  5308  22837  198708    209    6830      2937  15642
12  1994  5299  22188  206212    222    6868      3046  15949
13  2072  5290  22822  203718    215    6875      3126  16370
14  2146  5270  22805  205382    206    6841      3160  16755
H28
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平　成　23        NaN     834729    (2,990)     480418      227746
11         24        NaN     835576    (3,110)     478560      230215
12         25        NaN     838591    (3,146)     477502      234207
13         26        NaN     842716    (3,268)     475085      235892
14         27        NaN     841066       3341     475260      239448
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      41615        131      25301       13096
17          ２         都島      24827         45      15681        8437
18          ３         福島      21821        878      11638        6532
19          ４         此花      24754        103      11505        5749
20          ５         中央      45269         65      29363       14500
21          ６          西      34231        190      19930       10307
22          ７          港      27721        121      12946        6708
23          ８         大正      26354         59      12132        5921
24          ９        天王寺      17432         42      11454        7123
25         10         浪速      19188         76       9821        5182
26         11        西淀川      38080        124      19636        9810
27         12         淀川      54902        109      34034       15642
28         13        東淀川      46766         74      26901       12887
29         14         東成      23302        113      13036        6613
30         15         生野      37553        161      20249       10058
31         16          旭      23866         22      14121        6955
32         17         城東      44278        102      26777       13541
33         18         鶴見      37361         83      21156       10765
34         19        阿倍野      24550         12      16823        9446
35         20        住之江      51898        280      24190       11446
36         21         住吉      39293         22      24541       12233
37         22        東住吉      40905        281      23137       11616
38         23         平野      69758        214      38093       18596
39         24         西成      25342         34      12795        6285

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      252672      112385       30335       76516        5534        2143
11      248345      110288       30128       74634        5526        2070
12      243295      109766       30440       73678        5648        1998
13      239193      109121       30950       72530        5641        1994
14      235812      108659       31281       71610        5768        2072
15         NaN         NaN         NaN         NaN         NaN         NaN
16       12205        6402         851        5539          12         225
17        7244        2331         588        1741           2          25
18        5106        3074         749        2292          33          13
19        5756        4762        2144        2126         492         284
20       14863        6452         408        6032          12          37
21        9623        6234         932        5129         173          17
22        6238        5378        2316        2480         582         196
23        6211        5352        2428        2468         456         146
24        4331        1542         180        1359           3          15
25        4639        3101         686        2404          11          21
26        9826        6899        2881        3768         250         102
27       18392        6615        1035        5570          10          88
28       14014        3935        1044        2889           2         127
29        6423        2986         749        2217          20          10
30       10191        3766         806        2955           5          72
31        7166        1762         365        1388           9          38
32       13236        3857         934        2909          14          33
33       10391        4099        1739        2338          22          35
34        7377        1293         195        1097           1          15
35       12744       12136        5353        3292        3491         257
36       12308        2243         493        1735          15         135
37       11521        3727         999        2678          50          71
38       19497        7235        2121        5056          58          64
39        6510        3478        1285        2148          45          46

   Unnamed: 30 Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40  \
10       20514       12749        2471        5294       20679      191418
11       20682       12865        2522        5295       22742      194300
12       20950       13148        2494        5308       22837      198708
13       21248       13394        2555        5299       22188      206212
14       21660       13742        2628        5290       22822      203718
15         NaN         NaN         NaN         NaN         NaN         NaN
16         664         385         123         156         986        7784
17         370         204          98          68         807        5535
18         511         307         122          82         546        4587
19        1635        1282          53         300         694        5637
20         499         227          92         180        1070        7729
21         666         349          69         248         794        6210
22        1741         862          44         835         689        6466
23        1120         688          53         379         612        6740
24         198         118          49          31         431        3691
25         914         383         348         183         517        4615
26        1620        1151          79         390         980        8472
27         556         421          96          39        1715       11703
28         962         702          64         196        1694       13035
29         389         222         112          55         658        5954
30         687         504          91          92         928       11395
31         480         377          50          53         840        6564
32         845         509         120         216        1531       11001
33         774         498         121         155        1051        9982
34         234         173          42          19         749        5390
35        3001        2013         145         843        1041       10911
36         789         274          73         442        1093       10434
37         938         560         264         114        1085       11537
38        1308        1015         180         113        1657       20903
39         759         518         140         101         654        7443

   Unnamed: 41 Unnamed: 43 Unnamed: 44
10        (92)        7172     (2,898)
11       (200)        6934     (2,910)
12       (209)        6830     (2,937)
13       (222)        6868     (3,046)
14       (215)        6875     (3,126)
15         NaN         NaN         NaN
16          18         253         113
17           2          78          43
18           7        1452         871
19           5         237          98
20          12         119          53
21          35         380         155
22           9         305         112
23           5         252          54
24           2         101          40
25           9         199          67
26          10         371         114
27          18         191          91
28           6         112          68
29           3         269         110
30           3         456         158
31           5          61          17
32           3         234          99
33          10         264          73
34           6          46           6
35          17         362         263
36           6          58          16
37           9         410         272
38          12         498         202
39           3         167          31
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  23  834729    2990  480418  227746  252672  112385  30335  76516   5534
11  24  835576    3110  478560  230215  248345  110288  30128  74634   5526
12  25  838591    3146  477502  234207  243295  109766  30440  73678   5648
13  26  842716    3268  475085  235892  239193  109121  30950  72530   5641
14  27  841066    3341  475260  239448  235812  108659  31281  71610   5768

      バス  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車  特種用途車
10  2143  5294  20679  191418     92    7172      2898  15220
11  2070  5295  22742  194300    200    6934      2910  15387
12  1998  5308  22837  198708    209    6830      2937  15642
13  1994  5299  22188  206212    222    6868      3046  15949
14  2072  5290  22822  203718    215    6875      3126  16370
H27
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平　成　22        NaN     839638    (2,944)     482203      225228
11         23        NaN     834729    (2,990)     480418      227746
12         24        NaN     833298      -3110     478560      230215
13         25        NaN     836288    (3,146)     477502      234207
14         26        NaN     841924    (3,268)     475085      235892
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      41111      (135)      24780       12696
17          ２         都島      24922       (45)      15678        8246
18          ３         福島      21893      (888)      11626        6431
19          ４         此花      24485       (93)      11513        5672
20          ５         中央      44798       (65)      28716       14184
21          ６          西      34216      (187)      19653       10073
22          ７          港      27572      (115)      13053        6655
23          ８         大正      26378       (55)      12196        5883
24          ９        天王寺      17438       (44)      11366        6995
25         10         浪速      18882       (73)       9622        5049
26         11        西淀川      37885      (116)      19635        9648
27         12         淀川      54707      (111)      33855       15358
28         13        東淀川      47065       (72)      27256       12845
29         14         東成      23431      (114)      13055        6510
30         15         生野      37628      (160)      20277        9911
31         16          旭      23945       (23)      14210        6845
32         17         城東      44770      (104)      26914       13389
33         18         鶴見      37653       (73)      21290       10622
34         19        阿倍野      24507       (14)      16845        9349
35         20        住之江      52295      (240)      24407       11430
36         21         住吉      39335       (26)      24651       12082
37         22        東住吉      41637      (270)      23268       11543
38         23         平野      69915      (212)      38296       18245
39         24         西成      25456       (33)      12923        6231


    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  22  839638    2944  482203  225228  256975  114317  30635  78236   5446
11  23  834729    2990  480418  227746  252672  112385  30335  76516   5534
12  24  833298    3110  478560  230215  248345  110288  30128  74634   5526
13  25  836288    3146  477502  234207  243295  109766  30440  73678   5648
14  26  841924    3268  475085  235892  239193  109121  30950  72530   5641

      バス  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車  特種用途車
10  2071  5315  21106  192173     52    7357      2892  15096
11  2143  5294  20679  191418     92    7172      2898  15220
12  2070  5295  20464  194300    200    6934      2910  15387
13  1998  5308  20534  198708    209    6830      2937  15642
14  1994  5299  21396  206212    222    6868      3046  15949
H26
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10    平 成  21        NaN     848705    (2,956)     487518      223916
11         22        NaN     839638    (2,944)     482203      225228
12         23        NaN     834729    (2,990)     480418      227746
13         24        NaN     833298      -3110     478560      230215
14         25        NaN     836288    (3,146)     477502      234207
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      40474      (129)      24284       12283
17          ２         都島      24838       (46)      15786        8193
18          ３         福島      21787      (870)      11558        6290
19          ４         此花      24224       (85)      11525        5640
20          ５         中央      44071       (71)      28193       13844
21          ６          西      34135      (185)      19433        9837
22          ７          港      27522      (114)      13170        6654
23          ８         大正      26320       (54)      12378        5893
24          ９        天王寺      17305       (46)      11282        6831
25         10         浪速      18773       (65)       9581        4964
26         11        西淀川      37600      (117)      19823        9627
27         12         淀川      54381      (114)      33851       15299
28         13        東淀川      47211       (76)      27769       12929
29         14         東成      23564      (116)      13207        6527
30         15         生野      37446      (162)      20437        9830
31         16          旭      23894       (25)      14370        6830
32         17         城東      44729      (105)      27334       13432
33         18         鶴見      37201       (63)      21549       10575
34         19        阿倍野      23961       (14)      16735        9238
35         20        住之江      51456      (167)      24947       11519
36         21         住吉      39354       (23)      24987       12061
37         22        東住吉      41040      (263)      23488       11525
38         23         平野      69691      (202)      38787       18207
39         24         西成      25311       (34)      13028        6179

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      263602      116947       30977       80570        5400        2171
11      256975      114317       30635       78236        5446        2071
12      252672      112385       30335       76516        5534        2143
13      248345      110288       30128       74634        5526        2070
14      243295      109766       30440       73678        5648        1998
15         NaN         NaN         NaN         NaN         NaN         NaN
16       12001        6691         833        5842          16         217
17        7593        2367         579        1786           2          24
18        5268        3303         805        2459          39          12
19        5885        4595        2037        2142         416         290
20       14349        6756         473        6269          14          36
21        9596        6642         979        5448         215          15
22        6516        5097        2172        2440         485         211
23        6485        5303        2365        2500         438         132
24        4451        1647         178        1468           1          15
25        4617        3123         675        2437          11          17
26       10196        6771        2746        3772         253          90
27       18552        6804        1015        5777          12          85
28       14840        4057        1058        2997           2         116
29        6680        3086         759        2308          19          75
30       10607        3839         813        3021           5          69
31        7540        1810         368        1433           9          35
32       13902        3931         937        2976          18          31
33       10974        4060        1641        2398          21          32
34        7497        1235         200        1034           1          17
35       13428       11721        4903        3320        3498         197
36       12926        2282         502        1761          19         123
37       11963        3871        1039        2773          59          60
38       20580        7242        2068        5122          52          56
39        6849        3533        1295        2195          43          43

   Unnamed: 30 Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40  \
10       20755       12808        2550        5397       21193      192737
11       20411       12592        2504        5315       21106      192173
12       20514       12749        2471        5294       20679      191418
13       20682       12865        2522        5295       20464      194300
14       20950       13148        2494        5308       20534      198708
15         NaN         NaN         NaN         NaN         NaN         NaN
16         613         364          91         158         822        7574
17         448         233         147          68         726        5402
18         529         324         123          82         504        4437
19        1548        1194          49         305         595        5450
20         528         228         120         180         974        7454
21         698         384          63         251         701        6257
22        1706         821          40         845         618        6418
23        1084         674          46         364         507        6694
24         193         114          48          31         411        3651
25         815         340         292         183         367        4672
26        1570        1100          78         392         925        8056
27         546         421          87          38        1468       11420
28         937         681          60         196        1505       12707
29         405         231         118          56         602        5909
30         665         491          83          91         823       11139
31         447         351          43          53         742        6421
32         927         544         167         216        1533       10739
33         721         461         107         153         975        9604
34         235         171          46          18         652        5033
35        2769        1794         122         853         907       10654
36         793         288          64         441         988       10123
37         858         519         221         118        1134       11216
38        1202         928         159         115        1489       20413
39         713         492         120         101         566        7265

   Unnamed: 41 Unnamed: 43 Unnamed: 44
10        (52)        7384     (2,904)
11        (52)        7357     (2,892)
12        (92)        7172     (2,898)
13       (200)        6934       -2910
14       (209)        6830     (2,937)
15         NaN         NaN         NaN
16        (17)         273       (112)
17         (2)          85        (44)
18         (7)        1444       (863)
19         (4)         221        (81)
20        (16)         130        (55)
21        (36)         389       (149)
22         (8)         302       (106)
23         (6)         222        (48)
24         (3)         106        (43)
25         (5)         198        (60)
26         (7)         365       (110)
27        (26)         207        (88)
28         (5)         120        (71)
29         (4)         280       (112)
30         (5)         474       (157)
31         (4)          69        (21)
32         (5)         234       (100)
33         (6)         260        (57)
34         (6)          54         (8)
35         (9)         261       (158)
36         (8)          58        (15)
37         (8)         413       (255)
38        (10)         502       (192)
39         (2)         163        (32)
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  21  848705    2956  487518  223916  263602  116947  30977  80570   5400
11  22  839638    2944  482203  225228  256975  114317  30635  78236   5446
12  23  834729    2990  480418  227746  252672  112385  30335  76516   5534
13  24  833298    3110  478560  230215  248345  110288  30128  74634   5526
14  25  836288    3146  477502  234207  243295  109766  30440  73678   5648

      バス  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車  特種用途車
10  2171  5397  21193  192737     52    7384      2904  15358
11  2071  5315  21106  192173     52    7357      2892  15096
12  2143  5294  20679  191418     92    7172      2898  15220
13  2070  5295  20464  194300    200    6934      2910  15387
14  1998  5308  20534  198708    209    6830      2937  15642
H25
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10    平 成  20        NaN     863396    (2,868)     498570      228472
11         21        NaN     848705    (2,956)     487518      223916
12         22        NaN     837134    (2,944)     482203      225228
13         23        NaN     834729    (2,990)     480418      227746
14         24        NaN     835576      -3110     478560      230215
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      39958       -105      23732       11757
17          ２         都島      25017        -48      15838        8075
18          ３         福島      21917       -859      11581        6084
19          ４         此花      24059        -85      11461        5485
20          ５         中央      43966        -73      27852       13359
21          ６          西      34120       -180      19253        9597
22          ７          港      27553       -117      13209        6485
23          ８         大正      26407        -50      12553        5870
24          ９        天王寺      17248        -42      11196        6622
25         10         浪速      18751        -69       9481        4799
26         11        西淀川      37605       -114      19996        9529
27         12         淀川      53877       -111      33567       15044
28         13        東淀川      47443        -77      28042       12769
29         14         東成      23633       -119      13264        6459
30         15         生野      37416       -158      20547        9716
31         16          旭      23891        -25      14423        6746
32         17         城東      44823       -106      27518       13196
33         18         鶴見      37130        -59      21645       10468
34         19        阿倍野      23988        -12      16804        9112
35         20        住之江      51294       -183      25372       11500
36         21         住吉      39492        -22      25215       11943
37         22        東住吉      40946       -267      23592       11413
38         23         平野      69562       -199      39188       17977
39         24         西成      25480        -30      13231        6210

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      270098      120348       31474       83334        5540        2220
11      263602      116947       30977       80570        5400        2171
12      256975      114317       30635       78236        5446        2071
13      252672      112385       30335       76516        5534        2143
14      248345      110288       30128       74634        5526        2070
15         NaN         NaN         NaN         NaN         NaN         NaN
16       11975        6956         899        6009          48         196
17        7763        2403         578        1825           0          25
18        5497        3448         842        2557          49          25
19        5976        4504        1999        2125         380         284
20       14493        6958         484        6461          13          36
21        9656        6766         946        5601         219          16
22        6724        5085        2132        2438         515         271
23        6683        5295        2345        2517         433         113
24        4574        1687         175        1511           1          12
25        4682        3196         701        2484          11          17
26       10467        6828        2775        3805         248          79
27       18523        6679        1003        5662          14          77
28       15273        4055        1043        3010           2         143
29        6805        3078         750        2309          19          67
30       10831        3793         788        3001           4          70
31        7677        1847         366        1473           8          38
32       14322        4033         953        3062          18          33
33       11177        4106        1630        2454          22          30
34        7692        1269         217        1051           1          17
35       13872       11328        4671        3310        3347         203
36       13272        2337         508        1809          20         110
37       12179        3873        1019        2817          37          39
38       21211        7213        2019        5121          73         127
39        7021        3551        1285        2222          44          42

   Unnamed: 30 Unnamed: 31 Unnamed: 32 Unnamed: 33 Unnamed: 36 Unnamed: 39  \
10       20607       12749        2477        5381       21380      192770
11       20755       12808        2550        5397       21193      192737
12       20411       12592        2504        5315       21106      192173
13       20514       12749        2471        5294       20679      191418
14       20682       12865        2522        5295       22742      194300
15         NaN         NaN         NaN         NaN         NaN         NaN
16         609         348         102         159         957        7252
17         443         228         147          68         829        5388
18         529         326         121          82         532        4348
19        1523        1168          50         305         688        5374
20         550         250         120         180        1074        7360
21         692         382          59         251         750        6248
22        1697         762          81         854         719        6265
23        1075         676          42         357         572        6584
24         188         109          48          31         455        3605
25         809         340         286         183         445        4592
26        1527        1063          76         388         955        7858
27         558         416         101          41        1701       11087
28         912         661          55         196        1721       12448
29         398         226         116          56         694        5840
30         650         481          78          91         912       10960
31         417         325          40          52         820        6273
32         920         538         166         216        1569       10505
33         722         461         108         153        1015        9347
34         239         178          43          18         718        4885
35        2745        1778         128         839        1032       10336
36         791         289          61         441        1110        9874
37         845         513         213         119        1201       10961
38        1140         861         164         115        1607       19784
39         703         486         117         100         666        7126

   Unnamed: 40 Unnamed: 42 Unnamed: 43
10        (15)        7501     (2,853)
11        (52)        7384     (2,904)
12        (52)        7357     (2,892)
13        (92)        7172     (2,898)
14       (200)        6934       -2910
15         NaN         NaN         NaN
16        (16)         256         -89
17         (2)          91         -46
18         (7)        1454        -852
19         (4)         225         -81
20        (16)         136         -57
21        (32)         395        -148
22         (7)         307        -110
23         (5)         215         -45
24         (1)         105         -41
25         (5)         211         -64
26         (9)         362        -105
27        (28)         208         -83
28         (4)         122         -73
29         (5)         292        -114
30         (5)         484        -153
31         (4)          73         -21
32         (4)         245        -102
33         (6)         265         -53
34         (5)          56          -7
35         (9)         278        -174
36         (8)          55         -14
37         (9)         435        -258
38         (8)         503        -191
39         (1)         161         -29
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  20  863396    2868  498570  228472  270098  120348  31474  83334   5540
11  21  848705    2956  487518  223916  263602  116947  30977  80570   5400
12  22  837134    2944  482203  225228  256975  114317  30635  78236   5446
13  23  834729    2990  480418  227746  252672  112385  30335  76516   5534
14  24  835576    3110  478560  230215  248345  110288  30128  74634   5526

      バス  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車  特種用途車
10  2220  5381  21380  192770     15    7501      2853  15226
11  2171  5397  21193  192737     52    7384      2904  15358
12  2071  5315  21106  192173     52    7357      2892  15096
13  2143  5294  20679  191418     92    7172      2898  15220
14  2070  5295  22742  194300    200    6934      2910  15387

H24
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10    平 成  19        NaN     878268    (2,863)     508283      229573
11         20        NaN     863396    (2,868)     498570      228472
12         21        NaN     848705      -2956     487518      223916
13         22        NaN     837134      -2944     482203      225228
14         23        NaN     834729       2990     480418      227746
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      39816        101      23566       11456
17          ２         都島      24967         52      15789        7948
18          ３         福島      21892        902      11501        5916
19          ４         此花      23761         85      11397        5352
20          ５         中央      43592         76      27472       12899
21          ６          西      34080        164      19215        9421
22          ７          港      27703         96      13364        6391
23          ８         大正      26817         41      12821        5914
24          ９        天王寺      17265         40      11208        6521
25         10         浪速      18552         63       9323        4679
26         11        西淀川      37665         95      20236        9521
27         12         淀川      53962        100      33670       14869
28         13        東淀川      47141         85      28171       12755
29         14         東成      23562        110      13296        6365
30         15         生野      37369        133      20694        9638
31         16          旭      23839         20      14654        6828
32         17         城東      45165         98      27840       13139
33         18         鶴見      36897         49      21781       10373
34         19        阿倍野      24086          8      16887        9049
35         20        住之江      51001        182      25318       11343
36         21         住吉      39598         13      25470       11860
37         22        東住吉      40812        280      23691       11262
38         23         平野      69406        169      39538       17971
39         24         西成      25781         28      13516        6276

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      278710      125027       30826       88836        5365        2277
11      270098      120348       31474       83334        5540        2220
12      263602      116947       30977       80570        5400        2171
13      256975      114317       30635       78236        5446        2071
14      252672      112385       30335       76516        5534        2143
15         NaN         NaN         NaN         NaN         NaN         NaN
16       12110        7173         920        6189          64         199
17        7841        2452         570        1882           -          23
18        5585        3534         842        2643          49          24
19        6045        4560        2010        2149         401         292
20       14573        7316         503        6800          13          34
21        9794        6929         945        5758         226          15
22        6973        5126        2202        2441         483         307
23        6907        5421        2432        2543         446         108
24        4687        1739         174        1564           1          12
25        4644        3290         718        2552          20          10
26       10715        6888        2808        3840         240          75
27       18801        6851        1000        5837          14          78
28       15416        4106        1047        3056           3         131
29        6931        3137         749        2365          23          74
30       11056        3794         788        3002           4          69
31        7826        1853         345        1502           6          39
32       14701        4118         950        3150          18          34
33       11408        4120        1615        2483          22          29
34        7838        1322         229        1092           1          17
35       13975       11344        4622        3423        3299         196
36       13610        2386         499        1866          21         131
37       12429        3956        1018        2899          39          37
38       21567        7341        2064        5184          93         159
39        7240        3629        1285        2296          48          50

   Unnamed: 30 Unnamed: 31 Unnamed: 32 Unnamed: 33 Unnamed: 36 Unnamed: 39  \
10       21675       13630        2641        5404       21697      191667
11       20607       12749        2477        5381       21380      192770
12       20755       12808        2550        5397       21193      192737
13       20411       12592        2504        5315       21106      192173
14       20514       12749        2471        5294       20679      191418
15         NaN         NaN         NaN         NaN         NaN         NaN
16         605         348          98         159         824        7182
17         423         221         135          67         724        5456
18         529         328         119          82         462        4314
19        1443        1097          44         302         633        5191
20         565         257         128         180         940        7120
21         676         368          55         253         692        6145
22        1689         745          83         861         660        6262
23        1065         669          34         362         525        6680
24         185         112          42          31         413        3599
25         814         340         291         183         392        4497
26        1504        1042          72         390         893        7712
27         558         407         110          41        1548       11035
28         897         644          57         196        1592       12105
29         385         212         116          57         617        5745
30         662         499          72          91         874       10797
31         409         323          36          50         733        6077
32         947         553         178         216        1573       10407
33         715         456         104         155         964        9031
34         246         188          40          18         696        4853
35        2648        1701         127         820         937       10275
36         784         287          56         441         953        9811
37         888         566         202         120        1035       10714
38        1159         881         158         120        1427       19280
39         718         505         114          99         572        7130

   Unnamed: 40 Unnamed: 42 Unnamed: 43
10        (15)        7642     (2,848)
11        (15)        7501     (2,853)
12         -52        7384       -2904
13         -52        7357       -2892
14         -92        7172       -2898
15         NaN         NaN         NaN
16          15         267          86
17         NaN         100          52
18           1        1528         901
19           2         245          83
20          16         145          60
21          12         408         152
22         NaN         295          96
23           2         197          39
24         NaN         109          40
25           2         226          61
26           3         357          92
27          14         222          86
28           3         139          82
29           1         308         109
30           1         479         132
31         NaN          74          20
32           1         246          97
33           1         257          48
34           1          65           7
35           7         283         175
36           2          63          11
37           6         491         274
38           2         502         167
39         NaN         166          28
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  19  878268    2863  508283  229573  278710  125027  30826  88836   5365
11  20  863396    2868  498570  228472  270098  120348  31474  83334   5540
12  21  848705    2956  487518  223916  263602  116947  30977  80570   5400
13  22  837134    2944  482203  225228  256975  114317  30635  78236   5446
14  23  834729    2990  480418  227746  252672  112385  30335  76516   5534

      バス  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車  特種用途車
10  2277  5404  21697  191667     15    7642      2848  16271
11  2220  5381  21380  192770     15    7501      2853  15226
12  2171  5397  21193  192737     52    7384      2904  15358
13  2071  5315  21106  192173     52    7357      2892  15096
14  2143  5294  20679  191418     92    7172      2898  15220
H23
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平 成　18        NaN     890261    (2,761)     521956      227480
11         19        NaN     878268    (2,863)     508283      229573
12         20        NaN     863396    (2,868)     498570      228472
13         21        NaN     848705      -2956     487518      223916
14         22        NaN     839638      -2944     482203      225228
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      40195        -89      23526       11167
17          ２         都島      25161        -50      15874        7901
18          ３         福島      21971       -916      11355        5684
19          ４         此花      23496        -78      11404        5291
20          ５         中央      43554        -72      27194       12409
21          ６          西      34195       -160      19112        9197
22          ７          港      27889        -89      13371        6355
23          ８         大正      27148        -37      12946        5889
24          ９        天王寺      17391        -42      11202        6464
25         10         浪速      18541        -67       9190        4525
26         11        西淀川      37784        -89      20369        9426
27         12         淀川      54217        -94      33651       14601
28         13        東淀川      47698        -83      28531       12750
29         14         東成      23794       -112      13324        6258
30         15         生野      37904       -134      21013        9672
31         16          旭      24159        -19      14852        6888
32         17         城東      45353        -99      27915       13015
33         18         鶴見      36988        -47      21821       10280
34         19        阿倍野      24179         -7      16883        8952
35         20        住之江      50786       -180      25263       11227
36         21         住吉      39877        -11      25632       11758
37         22        東住吉      41092       -289      23821       11184
38         23         平野      69732       -153      39881       17923
39         24         西成      26534        -27      14073        6412

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      294476      126297       30737       90331        5229        2276
11      278710      125027       30826       88836        5365        2277
12      270098      120348       31474       83334        5540        2220
13      263602      116947       30977       80570        5400        2171
14      256975      114317       30635       78236        5446        2071
15         NaN         NaN         NaN         NaN         NaN         NaN
16       12359        7477         943        6471          63         214
17        7973        2513         579        1934           -          23
18        5671        3643         887        2708          48          21
19        6113        4476        1937        2195         344         247
20       14785        7459         512        6934          13          36
21        9915        7086         963        5907         216          16
22        7016        5149        2175        2488         486         293
23        7057        5460        2436        2547         477         109
24        4738        1843         177        1665           1          12
25        4665        3356         749        2592          15          13
26       10943        6898        2826        3833         239          75
27       19050        6979         990        5975          14          70
28       15781        4229        1077        3149           3         111
29        7066        3237         786        2428          23          74
30       11341        3873         799        3070           4          70
31        7964        1936         368        1562           6          40
32       14900        4128         919        3192          17          32
33       11541        4213        1700        2487          26          29
34        7931        1366         240        1125           1          16
35       14036       11422        4659        3524        3239         195
36       13874        2429         508        1904          17         129
37       12637        4037        1037        2958          42          36
38       21958        7359        2059        5195         105         154
39        7661        3749        1309        2393          47          56

   Unnamed: 30 Unnamed: 33 Unnamed: 36 Unnamed: 39 Unnamed: 40 Unnamed: 42  \
10       16668        5417       21561      188433        (16)        7653
11       16271        5404       21697      191667        (15)        7642
12       15226        5381       21380      192770        (15)        7501
13       15358        5397       21193      192737         -52        7384
14       15096        5315       21106      192173         -52        7357
15         NaN         NaN         NaN         NaN         NaN         NaN
16         457         160         844        7244          -4         273
17         393          68         775        5414         NaN         101
18         454          82         486        4375          -1        1555
19        1091         305         611        5119          -3         243
20         419         180         946        7171         -11         149
21         403         256         691        6208          -9         423
22         820         876         673        6414         NaN         293
23         735         361         550        6791          -2         196
24         147          31         421        3621          -2         114
25         633         183         406        4527          -2         233
26        1100         387         886        7713          -1         356
27         520          41        1550       11180          -9         226
28         710         199        1669       12109         NaN         140
29         338          58         615        5829         NaN         319
30         543          92         908       10917          -1         488
31         336          50         797        6073         NaN          75
32         732         215        1615       10448         NaN         268
33         548         156         956        8984         NaN         281
34         223          18         708        4897         NaN          68
35        1823         821         926       10037          -2         299
36         340         442         982        9856          -1          67
37         738         122        1031       10783          -4         524
38         984         114        1464       19279         NaN         497
39         609          98         596        7184         NaN         169

   Unnamed: 43
10     (2,745)
11     (2,848)
12     (2,853)
13       -2904
14       -2892
15         NaN
16         -85
17         -50
18        -915
19         -75
20         -61
21        -151
22         -89
23         -35
24         -40
25         -65
26         -88
27         -85
28         -83
29        -112
30        -133
31         -19
32         -99
33         -47
34          -7
35        -178
36         -10
37        -285
38        -153
39         -27
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  18  890261    2761  521956  227480  294476  126297  30737  90331   5229
11  19  878268    2863  508283  229573  278710  125027  30826  88836   5365
12  20  863396    2868  498570  228472  270098  120348  31474  83334   5540
13  21  848705    2956  487518  223916  263602  116947  30977  80570   5400
14  22  839638    2944  482203  225228  256975  114317  30635  78236   5446

      バス  特種用途車  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車
10  2276  16668  5417  21561  188433     16    7653      2745
11  2277  16271  5404  21697  191667     15    7642      2848
12  2220  15226  5381  21380  192770     15    7501      2853
13  2171  15358  5397  21193  192737     52    7384      2904
14  2071  15096  5315  21106  192173     52    7357      2892
H22
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平 成　17        NaN     897431    (2,771)     528491      228242
11         18        NaN     890261    (2,761)     521956      227480
12         19        NaN     878268    (2,863)     508283      229573
13         20        NaN     863396    (2,868)     498570      228472
14         21        NaN     848705      -2956     487518      223916
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      40684        -90      23639       10928
17          ２         都島      25292        -50      15939        7816
18          ３         福島      22110       -919      11242        5503
19          ４         此花      23560        -78      11569        5289
20          ５         中央      44051        -72      27165       12068
21          ６          西      34591       -160      19189        8964
22          ７          港      28107        -88      13499        6319
23          ８         大正      27350        -37      13144        5983
24          ９        天王寺      17438        -42      11161        6385
25         10         浪速      18660        -68       9208        4468
26         11        西淀川      37972        -91      20433        9395
27         12         淀川      54700        -95      33910       14443
28         13        東淀川      48422        -83      29056       12812
29         14         東成      24132       -112      13496        6246
30         15         生野      38475       -134      21467        9663
31         16          旭      24556        -19      15188        6909
32         17         城東      46159        -99      28459       12991
33         18         鶴見      37402        -47      22012       10149
34         19        阿倍野      24390         -7      17013        8952
35         20        住之江      51180       -180      25847       11329
36         21         住吉      40351        -11      26030       11794
37         22        東住吉      41592       -294      24147       11197
38         23         平野      70705       -153      40519       17921
39         24         西成      26826        -27      14186        6392

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      300249      131058       32430       93558        5070        2420
11      294476      126297       30737       90331        5229        2276
12      278710      125027       30826       88836        5365        2277
13      270098      120348       31474       83334        5540        2220
14      263602      116947       30977       80570        5400        2171
15         NaN         NaN         NaN         NaN         NaN         NaN
16       12711        7791         974        6754          63         222
17        8123        2570         574        1996           -          23
18        5739        3844         923        2869          52          23

H21
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平 成　16        NaN     899539    (2,736)     529975      225894
11         17        NaN     897431    (2,771)     528491      228242
12         18        NaN     890261    (2,761)     521956      227480
13         19        NaN     878268    (2,863)     508283      229573
14         20        NaN     864406    (2,868)     498570      228472
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      41784       (92)      24290       11181
17          ２         都島      25865       (47)      16331        8056
18          ３         福島      22484      (930)      11351        5510
19          ４         此花      23747       (52)      11887        5422
20          ５         中央      44427       (63)      27488       12038
21          ６          西      35246      (147)      19518        9024
22          ７          港      28475       (78)      13817        6378
23          ８         大正      27923       (21)      13516        6190
24          ９        天王寺      17766       (42)      11346        6395
25         10         浪速      19370       (62)       9634        4706
26         11        西淀川      38285       (88)      20634        9435
27         12         淀川      55600       (87)      34695       14731
28         13        東淀川      49602       (84)      29922       13143
29         14         東成      24624      (114)      13788        6434
30         15         生野      39536      (134)      22228       10114
31         16          旭      24951       (20)      15574        7061
32         17         城東      46708       (91)      28757       12956
33         18         鶴見      37878       (41)      22300       10214
34         19        阿倍野      24743        (8)      17237        9013
35         20        住之江      51910      (182)      26585       11653
36         21         住吉      41100       (12)      26747       12132
37         22        東住吉      43338      (300)      24835       11530
38         23         平野      71729      (145)      41560       18496
39         24         西成      27315       (28)      14530        6660

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      304081      137609       34714       97960        4935        2467
11      300249      131058       32430       93558        5070        2420
12      294476      126297       30737       90331        5229        2276
13      278710      125027       30826       88836        5365        2277
14      270098      120348       31474       83334        5540        2220
15         NaN         NaN         NaN         NaN         NaN         NaN
16       13109        8137         998        7073          66         208
17        8275        2731         614        2117           -          22
18        5841        4033         956        3019          58          21
19        6465        4427        1837        2250         340         232
20       15450        8146         578        7555          13          35
21       10494        7657        1037        6416         204          10
22        7439        5451        2294        2593         564         300
23        7326        5628        2551        2576         501         127
24        4951        2003         189        1814           -          11
25        4928        3504         780        2705          19          15
26       11199        7147        2881        4024         242          74
27       19964        7286         984        6284          18          64
28       16779        4501        1124        3371           6         115
29        7354        3564         877        2662          25          78
30       12114        4063         809        3250           4          72
31        8513        2073         394        1674           5          40
32       15801        4414         971        3425          18         131
33       12086        4487        1789        2650          48          32
34        8224        1484         233        1249           2          17
35       14932       11235        4466        3564        3205         249
36       14615        2558         536        2003          19         119
37       13305        4204        1078        3096          30          28
38       23064        7736        2151        5478         107         166
39        7870        3879        1347        2486          46          54

   Unnamed: 30 Unnamed: 33 Unnamed: 36 Unnamed: 39 Unnamed: 40 Unnamed: 42  \
10       17996        5449       21322      176946        (26)        7775
11       17333        5429       21769      183207        (22)        7724
12       16668        5417       21561      188433        (16)        7653
13       16271        5404       21697      191667        (15)        7642
14       15236        5381       21380      193770        (15)        7501
15         NaN         NaN         NaN         NaN         NaN         NaN
16         452         161         885        7376        ( 3)         275
17         373          69         815        5421         NaN         103
18         482          82         492        4429         NaN        1594
19        1053         311         590        5039         NaN         208
20         406         178         938        7085         NaN         151
21         435         256         724        6223        ( 5)         423
22         745         902         694        6282         NaN         284
23         747         334         563        6815         NaN         193
24         150          31         438        3667         NaN         120
25         667         194         428        4690        ( 3)         238
26        1124         385         898        7655         NaN         368
27         524          41        1516       11237         NaN         237
28         787         199        1703       12225         NaN         150
29         356          56         609        5844         NaN         329
30         561          96         906       11102         NaN         508
31         300          50         834        6001         NaN          79
32         850         216        1603       10463         NaN         274
33         548         166         948        9118         NaN         279
34         230          18         739        4945         NaN          73
35        1753         857         928        9988        ( 1)         315
36         320         444        1011        9829        ( 1)          72
37         692         122        1014       11881        ( 2)         562
38         992         112        1468       19201         NaN         494
39         689         101         636        7254         NaN         172

   Unnamed: 43
10     (2,710)
11     (2,749)
12     (2,745)
13     (2,848)
14     (2,853)
15         NaN
16        (89)
17        (47)
18       (930)
19        (52)
20        (63)
21       (142)
22        (78)
23        (21)
24        (42)
25        (59)
26        (88)
27        (87)
28        (84)
29       (114)
30       (134)
31        (20)
32        (91)
33        (41)
34         (8)
35       (181)
36        (11)
37       (298)
38       (145)
39        (28)
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車  貨物小型車 貨物被牽引車  \
10  16  899539    2736  529975  225894  304081  137609  34714  97960   4935
11  17  897431    2771  528491  228242  300249  131058  32430  93558   5070
12  18  890261    2761  521956  227480  294476  126297  30737  90331   5229
13  19  878268    2863  508283  229573  278710  125027  30826  88836   5365
14  20  864406    2868  498570  228472  270098  120348  31474  83334   5540

      バス  特種用途車  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車
10  2467  17996  5449  21322  176946     26    7775      2710
11  2420  17333  5429  21769  183207     22    7724      2749
12  2276  16668  5417  21561  188433     16    7653      2745
13  2277  16271  5404  21697  191667     15    7642      2848
14  2220  15236  5381  21380  193770     15    7501      2853
H20
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平 成　15        NaN     900212    (2,743)     530308      221585
11         16        NaN     899539    (2,736)     529975      225894
12         17        NaN     897431    (2,771)     528491      228242
13         18        NaN     890261    (2,761)     521956      227480
14         19        NaN     878268    (2,863)     508283      229573
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      42813       (91)      24810       11153
17          ２         都島      26293       (49)      16644        8120
18          ３         福島      22685      (918)      11402        5437
19          ４         此花      24079       (50)      12195        5455
20          ５         中央      44826       (67)      27623       11879
21          ６          西      36103      (150)      19869        9075
22          ７          港      28895       (82)      14182        6404
23          ８         大正      28378       (22)      13816        6247
24          ９        天王寺      18200       (42)      11545        6391
25         10         浪速      19755       (60)       9760        4751
26         11        西淀川      38983       (83)      21174        9544
27         12         淀川      56293       (85)      35099       14750
28         13        東淀川      50693       (86)      30600       13266
29         14         東成      25263      (118)      14180        6541
30         15         生野      40539      (127)      22766       10284
31         16          旭      25440       (23)      15921        7123
32         17         城東      47328       (87)      29276       13004
33         18         鶴見      37878       (37)      22502       10162
34         19        阿倍野      25240        (8)      17523        9012
35         20        住之江      52210      (210)      27072       11600
36         21         住吉      42115       (11)      27361       12211
37         22        東住吉      43175      (297)      25451       11662
38         23         平野      72856      (137)      42442       18649
39         24         西成      28228       (23)      15070        6853

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      308723      142416       35786      101924        4706        2473
11      304081      137609       34714       97960        4935        2467
12      300249      131058       32430       93558        5070        2420
13      294476      126297       30737       90331        5229        2276
14      278710      125027       30826       88836        5365        2277
15         NaN         NaN         NaN         NaN         NaN         NaN
16       13657        8484        1014        7403          67         225
17        8524        2954         621        2331           2          19
18        5965        4182         943        3174          65          19
19        6740        4564        1909        2332         323         221
20       15744        8406         568        7825          13          37
21       10794        8106        1063        6755         288          10
22        7778        5432        2136        2702         594         329
23        7569        5779        2505        2737         537         125
24        5154        2169         188        1981           0          15
25        5009        3704         800        2887          17          13
26       11630        7334        2859        4256         219          76
27       20349        7639        1012        6607          20          68
28       17334        4774        1095        3673           6         122
29        7639        3797         917        2853          27          94
30       12482        4417         777        3636           4          70
31        8798        2175         383        1788           4          35
32       16272        4673         991        3662          20         116
33       12340        4537        1734        2774          29          31
34        8511        1639         236        1401           2          13
35       15472       10931        4198        3794        2939         250
36       15150        2795         537        2239          19         138
37       13789        4458        1031        3399          28          27
38       23793        8013        1989        5927          97         170
39        8217        4065        1320        2700          45          54

   Unnamed: 30 Unnamed: 34 Unnamed: 37 Unnamed: 39 Unnamed: 40 Unnamed: 42  \
10       18869        5488       21041      171701        (35)        7916
11       17996        5449       21322      176946        (26)        7775
12       17333        5429       21769      183207        (22)        7724
13       16668        5417       21561      188433        (16)        7653
14       16271        5404       21697      191667        (15)        7642
15         NaN         NaN         NaN         NaN         NaN         NaN
16         504         NaN         911        7437        ( 3)         282
17         388         NaN         833        5281         NaN         107
18         470         NaN         510        4413         NaN        1606
19        1084         NaN         578        4931         NaN         204
20         460         NaN         939        7021         NaN         162
21         468         NaN         734        6223        ( 5)         435
22         798         NaN         709        6241         NaN         283
23         814         NaN         584        6744         NaN         190
24         150         NaN         462        3708         NaN         120
25         698         NaN         475        4667        ( 3)         243
26        1165         NaN         900        7577         NaN         370
27         579         NaN        1504       11124         NaN         239
28         899         NaN        1791       12146         NaN         162
29         371         NaN         600        5823         NaN         343
30         608         NaN         952       11109         NaN         517
31         304         NaN         868        6006         NaN          82
32         883         NaN        1572       10314         NaN         279
33         619         NaN         935        8802         NaN         278
34         244         NaN         741        4983         NaN          79
35        1831         NaN         921        9975        ( 1)         358
36         363         NaN        1030        9914        ( 1)          69
37         755         NaN        1038       10752        ( 2)         572
38        1054         NaN        1453       19123         NaN         492
39         762         NaN         657        7353         NaN         170

   Unnamed: 43
10     (2,708)
11     (2,710)
12     (2,749)
13     (2,745)
14     (2,848)
15         NaN
16        (88)
17        (49)
18       (918)
19        (50)
20        (67)
21       (145)
22        (82)
23        (22)
24        (42)
25        (57)
26        (83)
27        (85)
28        (86)
29       (118)
30       (127)
31        (23)
32        (87)
33        (37)
34         (8)
35       (209)
36        (10)
37       (295)
38       (137)
39        (23)
    年度      総数 電気自動車総数   乗用車総数   普通乗用車   小型乗用車   貨物車総数  貨物普通車   貨物小型車 貨物被牽引車  \
10  15  900212    2743  530308  221585  308723  142416  35786  101924   4706
11  16  899539    2736  529975  225894  304081  137609  34714   97960   4935
12  17  897431    2771  528491  228242  300249  131058  32430   93558   5070
13  18  890261    2761  521956  227480  294476  126297  30737   90331   5229
14  19  878268    2863  508283  229573  278710  125027  30826   88836   5365

      バス  特種用途車  大型特種   小型二輪    軽自動車 電気軽自動車 小型特殊自動車 電気小型特殊自動車
10  2473  18869  5488  21041  171701     35    7916      2708
11  2467  17996  5449  21322  176946     26    7775      2710
12  2420  17333  5429  21769  183207     22    7724      2749
13  2276  16668  5417  21561  188433     16    7653      2745
14  2277  16271  5404  21697  191667     15    7642      2848
H19
   Unnamed: 1 Unnamed: 2 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11  \
10     平　成　14        NaN     905738    (2,736)     533935      218448
11         15        NaN     900212    (2,743)     530308      221585
12         16        NaN     899539    (2,736)     529975      225894
13         17        NaN     897431    (2,771)     528491      228242
14         18        NaN     890261    (2,761)     521956      227480
15        NaN        NaN        NaN        NaN        NaN         NaN
16          １          北      43605       (87)      25207       11017
17          ２         都島      26646       (47)      17019        7997
18          ３         福島      22860      (904)      11613        5364
19          ４         此花      24124       (35)      12443        5395
20          ５         中央      45177       (65)      27809       11531
21          ６          西      36431      (154)      19912        8966
22          ７          港      28740       (77)      14246        6294
23          ８         大正      28727       (21)      14408        6292
24          ９        天王寺      18525       (40)      11726        6249
25         10         浪速      20126       (49)      10099        4683
26         11        西淀川      38927       (76)      21463        9285
27         12         淀川      57289       (77)      36032       14623
28         13        東淀川      51865       (92)      31916       13312
29         14         東成      25743      (114)      14655        6568
30         15         生野      41569      (137)      23790       10246
31         16          旭      25839       (22)      16484        7114
32         17         城東      47771       (89)      29888       12812
33         18         鶴見      38312       (39)      22970       10008
34         19        阿倍野      25530       ( 8)      17790        8852
35         20        住之江      52194      (167)      27987       11549
36         21         住吉      43225       (13)      28302       12276
37         22        東住吉      44018      (300)      26322       11628
38         23         平野      73976      (127)      44040       18600
39         24         西成      29042       (31)      15835        6819

   Unnamed: 14 Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28  \
10      315487      147711       37034      106034        4643        2454
11      308723      142416       35786      101924        4706        2473
12      304081      137609       34714       97960        4935        2467
13      300249      131058       32430       93558        5070        2420
14      294476      126297       30737       90331        5229        2276
15         NaN         NaN         NaN         NaN         NaN         NaN
16       14190        8717        1021        7633          63         209
17        9022        3043         650        2391           2          14
18        6249        4232         939        3242          51          19
19        7048        4492        1856        2333         303         240
20       16278        8549         600        7936          13          37
21       10946        8233        1118        6816         299          10
22        7952        5432        2051        2703         678         324
23        8116        5687        2471        2690         526         129
24        5477        2276         220        2056           0          15
25        5416        3814         820        2980          14          11
26       12178        7329        2861        4249         219          74
27       21409        7799        1073        6687          39          66
28       18604        4812        1078        3730           4         132

TypeError: object of type 'NoneType' has no len()

In [270]:
df28 = df['H14'].iloc[10:40, :]
df28 = df28.iloc[:5, [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]]
df28 = df28.T.dropna()
df28 = df28.T
df28.columns = [i for i in range(len(df28.columns))]
df28

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
10,945839,-2591,549522,186374,363148,180320,43376,132292,4652,2835,18416,5833,20384,160238,-90,8291,-2501
11,931917,-2633,548197,195662,352535,169856,41913,123384,4559,2740,19033,5791,20222,157838,-91,8240,-2542
12,921544,-2748,543083,203759,339324,163018,39669,118858,4491,2683,19295,5711,20154,159341,-95,8259,-2653
13,917210,-2789,539770,210901,328869,158380,39142,114631,4607,2637,19560,5669,20426,162574,-101,8194,-2688
14,913052,-2753,537677,216334,321343,153369,38250,110497,4622,2479,19813,5604,20827,165220,-88,8063,-2665

In [272]:
df['H20'].iloc[10:40, :]

,140 運輸及び通信,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,運輸及び通信 141
10,NaN,平 成 15,NaN,年,NaN,900212,"(2,743)",NaN,530308,NaN,NaN,221585,NaN,NaN,308723,NaN,NaN,142416,NaN,NaN,35786,NaN,NaN,101924,NaN,4706,NaN,NaN,2473,NaN,18869,NaN,NaN,NaN,5488,NaN,NaN,21041,NaN,171701,(35),NaN,7916,"(2,708)",NaN,15
11,NaN,16,NaN,年,NaN,899539,"(2,736)",NaN,529975,NaN,NaN,225894,NaN,NaN,304081,NaN,NaN,137609,NaN,NaN,34714,NaN,NaN,97960,NaN,4935,NaN,NaN,2467,NaN,17996,NaN,NaN,NaN,5449,NaN,NaN,21322,NaN,176946,(26),NaN,7775,"(2,710)",NaN,16
12,NaN,17,NaN,年,NaN,897431,"(2,771)",NaN,528491,NaN,NaN,228242,NaN,NaN,300249,NaN,NaN,131058,NaN,NaN,32430,NaN,NaN,93558,NaN,5070,NaN,NaN,2420,NaN,17333,NaN,NaN,NaN,5429,NaN,NaN,21769,NaN,183207,(22),NaN,7724,"(2,749)",NaN,17
13,NaN,18,NaN,年,NaN,890261,"(2,761)",NaN,521956,NaN,NaN,227480,NaN,NaN,294476,NaN,NaN,126297,NaN,NaN,30737,NaN,NaN,90331,NaN,5229,NaN,NaN,2276,NaN,16668,NaN,NaN,NaN,5417,NaN,NaN,21561,NaN,188433,(16),NaN,7653,"(2,745)",NaN,18
14,NaN,19,NaN,年,NaN,878268,"(2,863)",NaN,508283,NaN,NaN,229573,NaN,NaN,278710,NaN,NaN,125027,NaN,NaN,30826,NaN,NaN,88836,NaN,5365,NaN,NaN,2277,NaN,16271,NaN,NaN,NaN,5404,NaN,NaN,21697,NaN,191667,(15),NaN,7642,"(2,848)",NaN,19
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,１,北,NaN,NaN,42813,(91),NaN,24810,NaN,NaN,11153,NaN,NaN,13657,NaN,NaN,8484,NaN,NaN,1014,NaN,NaN,7403,NaN,67,NaN,NaN,225,NaN,504,NaN,NaN,160,NaN,NaN,NaN,911,NaN,7437,( 3),NaN,282,(88),NaN,１
17,,２,都島,都島,NaN,26293,(49),NaN,16644,NaN,NaN,8120,NaN,NaN,8524,NaN,NaN,2954,NaN,NaN,621,NaN,NaN,2331,NaN,2,NaN,NaN,19,NaN,388,NaN,NaN,67,NaN,NaN,NaN,833,NaN,5281,NaN,NaN,107,(49),NaN,２
18,NaN,３,福島,福島,NaN,22685,(918),NaN,11402,NaN,NaN,5437,NaN,NaN,5965,NaN,NaN,4182,NaN,NaN,943,NaN,NaN,3174,NaN,65,NaN,NaN,19,NaN,470,NaN,NaN,83,NaN,NaN,NaN,510,NaN,4413,NaN,NaN,1606,(918),NaN,３
19,NaN,４,此花,此花,NaN,24079,(50),NaN,12195,NaN,NaN,5455,NaN,NaN,6740,NaN,NaN,4564,NaN,NaN,1909,NaN,NaN,2332,NaN,323,NaN,NaN,221,NaN,1084,NaN,NaN,302,NaN,NaN,NaN,578,NaN,4931,NaN,NaN,204,(50),NaN,４
20,NaN,５,中央,中央,NaN,44826,(67),NaN,27623,NaN,NaN,11879,NaN,NaN,15744,NaN,NaN,8406,NaN,NaN,568,NaN,NaN,7825,NaN,13,NaN,NaN,37,NaN,460,NaN,NaN,178,NaN,NaN,NaN,939,NaN,7021,NaN,NaN,162,(67),NaN,５
21,NaN,６,西,西,NaN,36103,(150),NaN,19869,NaN,NaN,9075,NaN,NaN,10794,NaN,NaN,8106,NaN,NaN,1063,NaN,NaN,6755,NaN,288,NaN,NaN,10,NaN,468,NaN,NaN,258,NaN,NaN,NaN,734,NaN,6223,( 5),NaN,435,(145),NaN,６
22,NaN,７,港,港,NaN,28895,(82),NaN,14182,NaN,NaN,6404,NaN,NaN,7778,NaN,NaN,5432,NaN,NaN,2136,NaN,NaN,2702,NaN,594,NaN,NaN,329,NaN,798,NaN,NaN,921,NaN,NaN,NaN,709,NaN,6241,NaN,NaN,283,(82),NaN,７
23,NaN,８,大正,大正,NaN,28378,(22),NaN,13816,NaN,NaN,6247,NaN,NaN,7569,NaN,NaN,5779,NaN,NaN,2505,NaN,NaN,2737,NaN,537,NaN,NaN,125,NaN,814,NaN,NaN,326,NaN,NaN,NaN,584,NaN,6744,NaN,NaN,190,(22),NaN,８
24,NaN,９,天王寺,天王寺,NaN,18200,(42),NaN,11545,NaN,NaN,6391,NaN,NaN,5154,NaN,NaN,2169,NaN,NaN,188,NaN,NaN,1981,NaN,0,NaN,NaN,15,NaN,150,NaN,NaN,31,NaN,NaN,NaN,462,NaN,3708,NaN,NaN,120,(42),NaN,９
25,NaN,10,浪速,浪速,NaN,19755,(60),NaN,9760,NaN,NaN,4751,NaN,NaN,5009,NaN,NaN,3704,NaN,NaN,800,NaN,NaN,2887,NaN,17,NaN,NaN,13,NaN,698,NaN,NaN,195,NaN,NaN,NaN,475,NaN,4667,( 3),NaN,243,(57),NaN,10
26,NaN,11,西淀川,西淀川,NaN,38983,(83),NaN,21174,NaN,NaN,9544,NaN,NaN,11630,NaN,NaN,7334,NaN,NaN,2859,NaN,NaN,4256,NaN,219,NaN,NaN,76,NaN,1165,NaN,NaN,387,NaN,NaN,NaN,900,NaN,7577,NaN,NaN,370,(83),NaN,11
27,NaN,12,淀川,淀川,NaN,56293,(85),NaN,35099,NaN,NaN,14750,NaN,NaN,20349,NaN,NaN,7639,NaN,NaN,1012,NaN,NaN,6607,NaN,20,NaN,NaN,68,NaN,579,NaN,NaN,41,NaN,NaN,NaN,1504,NaN,11124,NaN,NaN,239,(85),NaN,12
28,NaN,13,東淀川,東淀川,NaN,50693,(86),NaN,30600,NaN,NaN,13266,NaN,NaN,17334,NaN,NaN,4774,NaN,NaN,1095,NaN,NaN,3673,NaN,6,NaN,NaN,122,NaN,899,NaN,NaN,199,NaN,NaN,NaN,1791,NaN,12146,NaN,NaN,162,(86),NaN,13
29,NaN,14,東成,東成,NaN,25263,(118),NaN,14180,NaN,NaN,6541,NaN,NaN,7639,NaN,NaN,3797,NaN,NaN,917,NaN,NaN,2853,NaN,27,NaN,NaN,94,NaN,371,NaN,NaN,55,NaN,NaN,NaN,600,NaN,5823,NaN,NaN,343,(118),NaN,14
30,NaN,15,生野,生野,NaN,40539,(127),NaN,22766,NaN,NaN,10284,NaN,NaN,12482,NaN,NaN,4417,NaN,NaN,777,NaN,NaN,3636,NaN,4,NaN,NaN,70,NaN,608,NaN,NaN,100,NaN,NaN,NaN,952,NaN,11109,NaN,NaN,517,(127),NaN,15
31,NaN,16,旭,旭,NaN,25440,(23),NaN,15921,NaN,NaN,7123,NaN,NaN,8798,NaN,NaN,2175,NaN,NaN,383,NaN,NaN,1788,NaN,4,NaN,NaN,35,NaN,304,NaN,NaN,49,NaN,NaN,NaN,868,NaN,6006,NaN,NaN,82,(23),NaN,16
32,NaN,17,城東,城東,NaN,47328,(87),NaN,29276,NaN,NaN,13004,NaN,NaN,16272,NaN,NaN,4673,NaN,NaN,991,NaN,NaN,3662,NaN,20,NaN,NaN,116,NaN,883,NaN,NaN,215,NaN,NaN,NaN,1572,NaN,10314,NaN,NaN,279,(87),NaN,17
33,NaN,18,鶴見,鶴見,NaN,37878,(37),NaN,22502,NaN,NaN,10162,NaN,NaN,12340,NaN,NaN,4537,NaN,NaN,1734,NaN,NaN,2774,NaN,29,NaN,NaN,31,NaN,619,NaN,NaN,174,NaN,NaN,NaN,935,NaN,8802,NaN,NaN,278,(37),NaN,18
34,NaN,19,阿倍野,阿倍野,NaN,25240,(8),NaN,17523,NaN,NaN,9012,NaN,NaN,8511,NaN,NaN,1639,NaN,NaN,236,NaN,NaN,1401,NaN,2,NaN,NaN,13,NaN,244,NaN,NaN,18,NaN,NaN,NaN,741,NaN,4983,NaN,NaN,79,(8),NaN,19
35,NaN,20,住之江,住之江,NaN,52210,(210),NaN,27072,NaN,NaN,11600,NaN,NaN,15472,NaN,NaN,10931,NaN,NaN,4198,NaN,NaN,3794,NaN,2939,NaN,NaN,250,NaN,1831,NaN,NaN,872,NaN,NaN,NaN,921,NaN,9975,( 1),NaN,358,(209),NaN,20
36,NaN,21,住吉,住吉,NaN,42115,(11),NaN,27361,NaN,NaN,12211,NaN,NaN,15150,NaN,NaN,2795,NaN,NaN,537,NaN,NaN,2239,NaN,19,NaN,NaN,138,NaN,363,NaN,NaN,445,NaN,NaN,NaN,1030,NaN,9914,( 1),NaN,69,(10),NaN,21
37,NaN,22,東住吉,東住吉,NaN,43175,(297),NaN,25451,NaN,NaN,11662,NaN,NaN,13789,NaN,NaN,4458,NaN,NaN,1031,NaN,NaN,3399,NaN,28,NaN,NaN,27,NaN,755,NaN,NaN,122,NaN,NaN,NaN,1038,NaN,10752,( 2),NaN,572,(295),NaN,22
38,NaN,23,平野,平野,NaN,72856,(137),NaN,42442,NaN,NaN,18649,NaN,NaN,23793,NaN,NaN,8013,NaN,NaN,1989,NaN,NaN,5927,NaN,97,NaN,NaN,170,NaN,1054,NaN,NaN,109,NaN,NaN,NaN,1453,NaN,19123,NaN,NaN,492,(137),NaN,23
39,NaN,24,西成,西成,NaN,28228,(23),NaN,15070,NaN,NaN,6853,NaN,NaN,8217,NaN,NaN,4065,NaN,NaN,1320,NaN,NaN,2700,NaN,45,NaN,NaN,54,NaN,762,NaN,NaN,97,NaN,NaN,NaN,657,NaN,7353,NaN,NaN,170,(23),NaN,24

In [232]:
df23 = df['H14'].iloc[10:40, :]
df23 = df23.iloc[:5,  [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]]
df23.columns = [i for i in range(len(df23.columns))]
df23

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
10,平成９,NaN,945839,-2591.0,549522,186374,363148,180320,43376,132292,4652,2835,18416,5833,20384,160238,-90.0,8291,-2501.0
11,NaN,10,931917,-2633.0,548197,195662,352535,169856,41913,123384,4559,2740,19033,5791,20222,157838,-91.0,8240,-2542.0
12,NaN,11,921544,-2748.0,543083,203759,339324,163018,39669,118858,4491,2683,19295,5711,20154,159341,-95.0,8259,-2653.0
13,NaN,12,917210,-2789.0,539770,210901,328869,158380,39142,114631,4607,2637,19560,5669,20426,162574,-101.0,8194,-2688.0
14,NaN,13,913052,-2753.0,537677,216334,321343,153369,38250,110497,4622,2479,19813,5604,20827,165220,-88.0,8063,-2665.0

In [207]:
[1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 31, 32, 33, 36, 39, 40, 42, 43]
df25 = df['H25'].iloc[10:40, :]
df25.columns = [i for i in range(len(df25.columns))]
df25

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46
10,NaN,平 成 20,NaN,年,NaN,863396,"(2,868)",NaN,498570,NaN,NaN,228472,NaN,NaN,270098,NaN,NaN,120348,NaN,NaN,31474,NaN,NaN,83334,NaN,5540,NaN,NaN,2220,NaN,20607,12749,2477,5381,NaN,NaN,21380,NaN,NaN,192770,(15),NaN,7501,"(2,853)",NaN,20,20
11,NaN,21,NaN,年,NaN,848705,"(2,956)",NaN,487518,NaN,NaN,223916,NaN,NaN,263602,NaN,NaN,116947,NaN,NaN,30977,NaN,NaN,80570,NaN,5400,NaN,NaN,2171,NaN,20755,12808,2550,5397,NaN,NaN,21193,NaN,NaN,192737,(52),NaN,7384,"(2,904)",NaN,21,21
12,NaN,22,NaN,年,NaN,837134,"(2,944)",NaN,482203,NaN,NaN,225228,NaN,NaN,256975,NaN,NaN,114317,NaN,NaN,30635,NaN,NaN,78236,NaN,5446,NaN,NaN,2071,NaN,20411,12592,2504,5315,NaN,NaN,21106,NaN,NaN,192173,(52),NaN,7357,"(2,892)",NaN,22,22
13,NaN,23,NaN,年,NaN,834729,"(2,990)",NaN,480418,NaN,NaN,227746,NaN,NaN,252672,NaN,NaN,112385,NaN,NaN,30335,NaN,NaN,76516,NaN,5534,NaN,NaN,2143,NaN,20514,12749,2471,5294,NaN,NaN,20679,NaN,NaN,191418,(92),NaN,7172,"(2,898)",NaN,23,23
14,NaN,24,NaN,年,NaN,835576,-3110,NaN,478560,NaN,NaN,230215,NaN,NaN,248345,NaN,NaN,110288,NaN,NaN,30128,NaN,NaN,74634,NaN,5526,NaN,NaN,2070,NaN,20682,12865,2522,5295,NaN,NaN,22742,NaN,NaN,194300,(200),NaN,6934,-2910,NaN,24,24
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,１,北,NaN,NaN,39958,-105,NaN,23732,NaN,NaN,11757,NaN,NaN,11975,NaN,NaN,6956,NaN,NaN,899,NaN,NaN,6009,NaN,48,NaN,NaN,196,NaN,609,348,102,159,NaN,NaN,957,NaN,NaN,7252,(16),NaN,256,-89,NaN,１,１
17,,２,都島,都島,NaN,25017,-48,NaN,15838,NaN,NaN,8075,NaN,NaN,7763,NaN,NaN,2403,NaN,NaN,578,NaN,NaN,1825,NaN,0,NaN,NaN,25,NaN,443,228,147,68,NaN,NaN,829,NaN,NaN,5388,(2),NaN,91,-46,NaN,２,２
18,NaN,３,福島,福島,NaN,21917,-859,NaN,11581,NaN,NaN,6084,NaN,NaN,5497,NaN,NaN,3448,NaN,NaN,842,NaN,NaN,2557,NaN,49,NaN,NaN,25,NaN,529,326,121,82,NaN,NaN,532,NaN,NaN,4348,(7),NaN,1454,-852,NaN,３,３
19,NaN,４,此花,此花,NaN,24059,-85,NaN,11461,NaN,NaN,5485,NaN,NaN,5976,NaN,NaN,4504,NaN,NaN,1999,NaN,NaN,2125,NaN,380,NaN,NaN,284,NaN,1523,1168,50,305,NaN,NaN,688,NaN,NaN,5374,(4),NaN,225,-81,NaN,４,４
20,NaN,５,中央,中央,NaN,43966,-73,NaN,27852,NaN,NaN,13359,NaN,NaN,14493,NaN,NaN,6958,NaN,NaN,484,NaN,NaN,6461,NaN,13,NaN,NaN,36,NaN,550,250,120,180,NaN,NaN,1074,NaN,NaN,7360,(16),NaN,136,-57,NaN,５,５
21,NaN,６,西,西,NaN,34120,-180,NaN,19253,NaN,NaN,9597,NaN,NaN,9656,NaN,NaN,6766,NaN,NaN,946,NaN,NaN,5601,NaN,219,NaN,NaN,16,NaN,692,382,59,251,NaN,NaN,750,NaN,NaN,6248,(32),NaN,395,-148,NaN,６,６
22,NaN,７,港,港,NaN,27553,-117,NaN,13209,NaN,NaN,6485,NaN,NaN,6724,NaN,NaN,5085,NaN,NaN,2132,NaN,NaN,2438,NaN,515,NaN,NaN,271,NaN,1697,762,81,854,NaN,NaN,719,NaN,NaN,6265,(7),NaN,307,-110,NaN,７,７
23,NaN,８,大正,大正,NaN,26407,-50,NaN,12553,NaN,NaN,5870,NaN,NaN,6683,NaN,NaN,5295,NaN,NaN,2345,NaN,NaN,2517,NaN,433,NaN,NaN,113,NaN,1075,676,42,357,NaN,NaN,572,NaN,NaN,6584,(5),NaN,215,-45,NaN,８,８
24,NaN,９,天王寺,天王寺,NaN,17248,-42,NaN,11196,NaN,NaN,6622,NaN,NaN,4574,NaN,NaN,1687,NaN,NaN,175,NaN,NaN,1511,NaN,1,NaN,NaN,12,NaN,188,109,48,31,NaN,NaN,455,NaN,NaN,3605,(1),NaN,105,-41,NaN,９,９
25,NaN,10,浪速,浪速,NaN,18751,-69,NaN,9481,NaN,NaN,4799,NaN,NaN,4682,NaN,NaN,3196,NaN,NaN,701,NaN,NaN,2484,NaN,11,NaN,NaN,17,NaN,809,340,286,183,NaN,NaN,445,NaN,NaN,4592,(5),NaN,211,-64,NaN,10,10
26,NaN,11,西淀川,西淀川,NaN,37605,-114,NaN,19996,NaN,NaN,9529,NaN,NaN,10467,NaN,NaN,6828,NaN,NaN,2775,NaN,NaN,3805,NaN,248,NaN,NaN,79,NaN,1527,1063,76,388,NaN,NaN,955,NaN,NaN,7858,(9),NaN,362,-105,NaN,11,11
27,NaN,12,淀川,淀川,NaN,53877,-111,NaN,33567,NaN,NaN,15044,NaN,NaN,18523,NaN,NaN,6679,NaN,NaN,1003,NaN,NaN,5662,NaN,14,NaN,NaN,77,NaN,558,416,101,41,NaN,NaN,1701,NaN,NaN,11087,(28),NaN,208,-83,NaN,12,12
28,NaN,13,東淀川,東淀川,NaN,47443,-77,NaN,28042,NaN,NaN,12769,NaN,NaN,15273,NaN,NaN,4055,NaN,NaN,1043,NaN,NaN,3010,NaN,2,NaN,NaN,143,NaN,912,661,55,196,NaN,NaN,1721,NaN,NaN,12448,(4),NaN,122,-73,NaN,13,13
29,NaN,14,東成,東成,NaN,23633,-119,NaN,13264,NaN,NaN,6459,NaN,NaN,6805,NaN,NaN,3078,NaN,NaN,750,NaN,NaN,2309,NaN,19,NaN,NaN,67,NaN,398,226,116,56,NaN,NaN,694,NaN,NaN,5840,(5),NaN,292,-114,NaN,14,14
30,NaN,15,生野,生野,NaN,37416,-158,NaN,20547,NaN,NaN,9716,NaN,NaN,10831,NaN,NaN,3793,NaN,NaN,788,NaN,NaN,3001,NaN,4,NaN,NaN,70,NaN,650,481,78,91,NaN,NaN,912,NaN,NaN,10960,(5),NaN,484,-153,NaN,15,15
31,NaN,16,旭,旭,NaN,23891,-25,NaN,14423,NaN,NaN,6746,NaN,NaN,7677,NaN,NaN,1847,NaN,NaN,366,NaN,NaN,1473,NaN,8,NaN,NaN,38,NaN,417,325,40,52,NaN,NaN,820,NaN,NaN,6273,(4),NaN,73,-21,NaN,16,16
32,NaN,17,城東,城東,NaN,44823,-106,NaN,27518,NaN,NaN,13196,NaN,NaN,14322,NaN,NaN,4033,NaN,NaN,953,NaN,NaN,3062,NaN,18,NaN,NaN,33,NaN,920,538,166,216,NaN,NaN,1569,NaN,NaN,10505,(4),NaN,245,-102,NaN,17,17
33,NaN,18,鶴見,鶴見,NaN,37130,-59,NaN,21645,NaN,NaN,10468,NaN,NaN,11177,NaN,NaN,4106,NaN,NaN,1630,NaN,NaN,2454,NaN,22,NaN,NaN,30,NaN,722,461,108,153,NaN,NaN,1015,NaN,NaN,9347,(6),NaN,265,-53,NaN,18,18
34,NaN,19,阿倍野,阿倍野,NaN,23988,-12,NaN,16804,NaN,NaN,9112,NaN,NaN,7692,NaN,NaN,1269,NaN,NaN,217,NaN,NaN,1051,NaN,1,NaN,NaN,17,NaN,239,178,43,18,NaN,NaN,718,NaN,NaN,4885,(5),NaN,56,-7,NaN,19,19
35,NaN,20,住之江,住之江,NaN,51294,-183,NaN,25372,NaN,NaN,11500,NaN,NaN,13872,NaN,NaN,11328,NaN,NaN,4671,NaN,NaN,3310,NaN,3347,NaN,NaN,203,NaN,2745,1778,128,839,NaN,NaN,1032,NaN,NaN,10336,(9),NaN,278,-174,NaN,20,20
36,NaN,21,住吉,住吉,NaN,39492,-22,NaN,25215,NaN,NaN,11943,NaN,NaN,13272,NaN,NaN,2337,NaN,NaN,508,NaN,NaN,1809,NaN,20,NaN,NaN,110,NaN,791,289,61,441,NaN,NaN,1110,NaN,NaN,9874,(8),NaN,55,-14,NaN,21,21
37,NaN,22,東住吉,東住吉,NaN,40946,-267,NaN,23592,NaN,NaN,11413,NaN,NaN,12179,NaN,NaN,3873,NaN,NaN,1019,NaN,NaN,2817,NaN,37,NaN,NaN,39,NaN,845,513,213,119,NaN,NaN,1201,NaN,NaN,10961,(9),NaN,435,-258,NaN,22,22
38,NaN,23,平野,平野,NaN,69562,-199,NaN,39188,NaN,NaN,17977,NaN,NaN,21211,NaN,NaN,7213,NaN,NaN,2019,NaN,NaN,5121,NaN,73,NaN,NaN,127,NaN,1140,861,164,115,NaN,NaN,1607,NaN,NaN,19784,(8),NaN,503,-191,NaN,23,23
39,NaN,24,西成,西成,NaN,25480,-30,NaN,13231,NaN,NaN,6210,NaN,NaN,7021,NaN,NaN,3551,NaN,NaN,1285,NaN,NaN,2222,NaN,44,NaN,NaN,42,NaN,703,486,117,100,NaN,NaN,666,NaN,NaN,7126,(1),NaN,161,-29,NaN,24,24

In [175]:
df['H20'].iloc[10:40, [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 33, 36, 39, 40, 42, 43]]

,Unnamed: 1,Unnamed: 2,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 11,Unnamed: 14,Unnamed: 17,Unnamed: 20,Unnamed: 23,Unnamed: 25,Unnamed: 28,Unnamed: 30,Unnamed: 33,Unnamed: 36,Unnamed: 39,Unnamed: 40,Unnamed: 42,Unnamed: 43
10,平 成 15,NaN,900212,"(2,743)",530308,221585,308723,142416,35786,101924,4706,2473,18869,NaN,NaN,171701,(35),7916,"(2,708)"
11,16,NaN,899539,"(2,736)",529975,225894,304081,137609,34714,97960,4935,2467,17996,NaN,NaN,176946,(26),7775,"(2,710)"
12,17,NaN,897431,"(2,771)",528491,228242,300249,131058,32430,93558,5070,2420,17333,NaN,NaN,183207,(22),7724,"(2,749)"
13,18,NaN,890261,"(2,761)",521956,227480,294476,126297,30737,90331,5229,2276,16668,NaN,NaN,188433,(16),7653,"(2,745)"
14,19,NaN,878268,"(2,863)",508283,229573,278710,125027,30826,88836,5365,2277,16271,NaN,NaN,191667,(15),7642,"(2,848)"
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,１,北,42813,(91),24810,11153,13657,8484,1014,7403,67,225,504,160,NaN,7437,( 3),282,(88)
17,２,都島,26293,(49),16644,8120,8524,2954,621,2331,2,19,388,67,NaN,5281,NaN,107,(49)
18,３,福島,22685,(918),11402,5437,5965,4182,943,3174,65,19,470,83,NaN,4413,NaN,1606,(918)
19,４,此花,24079,(50),12195,5455,6740,4564,1909,2332,323,221,1084,302,NaN,4931,NaN,204,(50)
20,５,中央,44826,(67),27623,11879,15744,8406,568,7825,13,37,460,178,NaN,7021,NaN,162,(67)
21,６,西,36103,(150),19869,9075,10794,8106,1063,6755,288,10,468,258,NaN,6223,( 5),435,(145)
22,７,港,28895,(82),14182,6404,7778,5432,2136,2702,594,329,798,921,NaN,6241,NaN,283,(82)
23,８,大正,28378,(22),13816,6247,7569,5779,2505,2737,537,125,814,326,NaN,6744,NaN,190,(22)
24,９,天王寺,18200,(42),11545,6391,5154,2169,188,1981,0,15,150,31,NaN,3708,NaN,120,(42)
25,10,浪速,19755,(60),9760,4751,5009,3704,800,2887,17,13,698,195,NaN,4667,( 3),243,(57)
26,11,西淀川,38983,(83),21174,9544,11630,7334,2859,4256,219,76,1165,387,NaN,7577,NaN,370,(83)
27,12,淀川,56293,(85),35099,14750,20349,7639,1012,6607,20,68,579,41,NaN,11124,NaN,239,(85)
28,13,東淀川,50693,(86),30600,13266,17334,4774,1095,3673,6,122,899,199,NaN,12146,NaN,162,(86)
29,14,東成,25263,(118),14180,6541,7639,3797,917,2853,27,94,371,55,NaN,5823,NaN,343,(118)
30,15,生野,40539,(127),22766,10284,12482,4417,777,3636,4,70,608,100,NaN,11109,NaN,517,(127)
31,16,旭,25440,(23),15921,7123,8798,2175,383,1788,4,35,304,49,NaN,6006,NaN,82,(23)
32,17,城東,47328,(87),29276,13004,16272,4673,991,3662,20,116,883,215,NaN,10314,NaN,279,(87)
33,18,鶴見,37878,(37),22502,10162,12340,4537,1734,2774,29,31,619,174,NaN,8802,NaN,278,(37)
34,19,阿倍野,25240,(8),17523,9012,8511,1639,236,1401,2,13,244,18,NaN,4983,NaN,79,(8)
35,20,住之江,52210,(210),27072,11600,15472,10931,4198,3794,2939,250,1831,872,NaN,9975,( 1),358,(209)
36,21,住吉,42115,(11),27361,12211,15150,2795,537,2239,19,138,363,445,NaN,9914,( 1),69,(10)
37,22,東住吉,43175,(297),25451,11662,13789,4458,1031,3399,28,27,755,122,NaN,10752,( 2),572,(295)
38,23,平野,72856,(137),42442,18649,23793,8013,1989,5927,97,170,1054,109,NaN,19123,NaN,492,(137)
39,24,西成,28228,(23),15070,6853,8217,4065,1320,2700,45,54,762,97,NaN,7353,NaN,170,(23)

In [179]:
[1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 34, 37, 39, 40, 42, 43]

df20 = df['H20'].iloc[10:40, :]
df20.columns = [x for x in range(len(df20.columns))]
df20

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45
10,NaN,平 成 15,NaN,年,NaN,900212,"(2,743)",NaN,530308,NaN,NaN,221585,NaN,NaN,308723,NaN,NaN,142416,NaN,NaN,35786,NaN,NaN,101924,NaN,4706,NaN,NaN,2473,NaN,18869,NaN,NaN,NaN,5488,NaN,NaN,21041,NaN,171701,(35),NaN,7916,"(2,708)",NaN,15
11,NaN,16,NaN,年,NaN,899539,"(2,736)",NaN,529975,NaN,NaN,225894,NaN,NaN,304081,NaN,NaN,137609,NaN,NaN,34714,NaN,NaN,97960,NaN,4935,NaN,NaN,2467,NaN,17996,NaN,NaN,NaN,5449,NaN,NaN,21322,NaN,176946,(26),NaN,7775,"(2,710)",NaN,16
12,NaN,17,NaN,年,NaN,897431,"(2,771)",NaN,528491,NaN,NaN,228242,NaN,NaN,300249,NaN,NaN,131058,NaN,NaN,32430,NaN,NaN,93558,NaN,5070,NaN,NaN,2420,NaN,17333,NaN,NaN,NaN,5429,NaN,NaN,21769,NaN,183207,(22),NaN,7724,"(2,749)",NaN,17
13,NaN,18,NaN,年,NaN,890261,"(2,761)",NaN,521956,NaN,NaN,227480,NaN,NaN,294476,NaN,NaN,126297,NaN,NaN,30737,NaN,NaN,90331,NaN,5229,NaN,NaN,2276,NaN,16668,NaN,NaN,NaN,5417,NaN,NaN,21561,NaN,188433,(16),NaN,7653,"(2,745)",NaN,18
14,NaN,19,NaN,年,NaN,878268,"(2,863)",NaN,508283,NaN,NaN,229573,NaN,NaN,278710,NaN,NaN,125027,NaN,NaN,30826,NaN,NaN,88836,NaN,5365,NaN,NaN,2277,NaN,16271,NaN,NaN,NaN,5404,NaN,NaN,21697,NaN,191667,(15),NaN,7642,"(2,848)",NaN,19
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,１,北,NaN,NaN,42813,(91),NaN,24810,NaN,NaN,11153,NaN,NaN,13657,NaN,NaN,8484,NaN,NaN,1014,NaN,NaN,7403,NaN,67,NaN,NaN,225,NaN,504,NaN,NaN,160,NaN,NaN,NaN,911,NaN,7437,( 3),NaN,282,(88),NaN,１
17,,２,都島,都島,NaN,26293,(49),NaN,16644,NaN,NaN,8120,NaN,NaN,8524,NaN,NaN,2954,NaN,NaN,621,NaN,NaN,2331,NaN,2,NaN,NaN,19,NaN,388,NaN,NaN,67,NaN,NaN,NaN,833,NaN,5281,NaN,NaN,107,(49),NaN,２
18,NaN,３,福島,福島,NaN,22685,(918),NaN,11402,NaN,NaN,5437,NaN,NaN,5965,NaN,NaN,4182,NaN,NaN,943,NaN,NaN,3174,NaN,65,NaN,NaN,19,NaN,470,NaN,NaN,83,NaN,NaN,NaN,510,NaN,4413,NaN,NaN,1606,(918),NaN,３
19,NaN,４,此花,此花,NaN,24079,(50),NaN,12195,NaN,NaN,5455,NaN,NaN,6740,NaN,NaN,4564,NaN,NaN,1909,NaN,NaN,2332,NaN,323,NaN,NaN,221,NaN,1084,NaN,NaN,302,NaN,NaN,NaN,578,NaN,4931,NaN,NaN,204,(50),NaN,４
20,NaN,５,中央,中央,NaN,44826,(67),NaN,27623,NaN,NaN,11879,NaN,NaN,15744,NaN,NaN,8406,NaN,NaN,568,NaN,NaN,7825,NaN,13,NaN,NaN,37,NaN,460,NaN,NaN,178,NaN,NaN,NaN,939,NaN,7021,NaN,NaN,162,(67),NaN,５
21,NaN,６,西,西,NaN,36103,(150),NaN,19869,NaN,NaN,9075,NaN,NaN,10794,NaN,NaN,8106,NaN,NaN,1063,NaN,NaN,6755,NaN,288,NaN,NaN,10,NaN,468,NaN,NaN,258,NaN,NaN,NaN,734,NaN,6223,( 5),NaN,435,(145),NaN,６
22,NaN,７,港,港,NaN,28895,(82),NaN,14182,NaN,NaN,6404,NaN,NaN,7778,NaN,NaN,5432,NaN,NaN,2136,NaN,NaN,2702,NaN,594,NaN,NaN,329,NaN,798,NaN,NaN,921,NaN,NaN,NaN,709,NaN,6241,NaN,NaN,283,(82),NaN,７
23,NaN,８,大正,大正,NaN,28378,(22),NaN,13816,NaN,NaN,6247,NaN,NaN,7569,NaN,NaN,5779,NaN,NaN,2505,NaN,NaN,2737,NaN,537,NaN,NaN,125,NaN,814,NaN,NaN,326,NaN,NaN,NaN,584,NaN,6744,NaN,NaN,190,(22),NaN,８
24,NaN,９,天王寺,天王寺,NaN,18200,(42),NaN,11545,NaN,NaN,6391,NaN,NaN,5154,NaN,NaN,2169,NaN,NaN,188,NaN,NaN,1981,NaN,0,NaN,NaN,15,NaN,150,NaN,NaN,31,NaN,NaN,NaN,462,NaN,3708,NaN,NaN,120,(42),NaN,９
25,NaN,10,浪速,浪速,NaN,19755,(60),NaN,9760,NaN,NaN,4751,NaN,NaN,5009,NaN,NaN,3704,NaN,NaN,800,NaN,NaN,2887,NaN,17,NaN,NaN,13,NaN,698,NaN,NaN,195,NaN,NaN,NaN,475,NaN,4667,( 3),NaN,243,(57),NaN,10
26,NaN,11,西淀川,西淀川,NaN,38983,(83),NaN,21174,NaN,NaN,9544,NaN,NaN,11630,NaN,NaN,7334,NaN,NaN,2859,NaN,NaN,4256,NaN,219,NaN,NaN,76,NaN,1165,NaN,NaN,387,NaN,NaN,NaN,900,NaN,7577,NaN,NaN,370,(83),NaN,11
27,NaN,12,淀川,淀川,NaN,56293,(85),NaN,35099,NaN,NaN,14750,NaN,NaN,20349,NaN,NaN,7639,NaN,NaN,1012,NaN,NaN,6607,NaN,20,NaN,NaN,68,NaN,579,NaN,NaN,41,NaN,NaN,NaN,1504,NaN,11124,NaN,NaN,239,(85),NaN,12
28,NaN,13,東淀川,東淀川,NaN,50693,(86),NaN,30600,NaN,NaN,13266,NaN,NaN,17334,NaN,NaN,4774,NaN,NaN,1095,NaN,NaN,3673,NaN,6,NaN,NaN,122,NaN,899,NaN,NaN,199,NaN,NaN,NaN,1791,NaN,12146,NaN,NaN,162,(86),NaN,13
29,NaN,14,東成,東成,NaN,25263,(118),NaN,14180,NaN,NaN,6541,NaN,NaN,7639,NaN,NaN,3797,NaN,NaN,917,NaN,NaN,2853,NaN,27,NaN,NaN,94,NaN,371,NaN,NaN,55,NaN,NaN,NaN,600,NaN,5823,NaN,NaN,343,(118),NaN,14
30,NaN,15,生野,生野,NaN,40539,(127),NaN,22766,NaN,NaN,10284,NaN,NaN,12482,NaN,NaN,4417,NaN,NaN,777,NaN,NaN,3636,NaN,4,NaN,NaN,70,NaN,608,NaN,NaN,100,NaN,NaN,NaN,952,NaN,11109,NaN,NaN,517,(127),NaN,15
31,NaN,16,旭,旭,NaN,25440,(23),NaN,15921,NaN,NaN,7123,NaN,NaN,8798,NaN,NaN,2175,NaN,NaN,383,NaN,NaN,1788,NaN,4,NaN,NaN,35,NaN,304,NaN,NaN,49,NaN,NaN,NaN,868,NaN,6006,NaN,NaN,82,(23),NaN,16
32,NaN,17,城東,城東,NaN,47328,(87),NaN,29276,NaN,NaN,13004,NaN,NaN,16272,NaN,NaN,4673,NaN,NaN,991,NaN,NaN,3662,NaN,20,NaN,NaN,116,NaN,883,NaN,NaN,215,NaN,NaN,NaN,1572,NaN,10314,NaN,NaN,279,(87),NaN,17
33,NaN,18,鶴見,鶴見,NaN,37878,(37),NaN,22502,NaN,NaN,10162,NaN,NaN,12340,NaN,NaN,4537,NaN,NaN,1734,NaN,NaN,2774,NaN,29,NaN,NaN,31,NaN,619,NaN,NaN,174,NaN,NaN,NaN,935,NaN,8802,NaN,NaN,278,(37),NaN,18
34,NaN,19,阿倍野,阿倍野,NaN,25240,(8),NaN,17523,NaN,NaN,9012,NaN,NaN,8511,NaN,NaN,1639,NaN,NaN,236,NaN,NaN,1401,NaN,2,NaN,NaN,13,NaN,244,NaN,NaN,18,NaN,NaN,NaN,741,NaN,4983,NaN,NaN,79,(8),NaN,19
35,NaN,20,住之江,住之江,NaN,52210,(210),NaN,27072,NaN,NaN,11600,NaN,NaN,15472,NaN,NaN,10931,NaN,NaN,4198,NaN,NaN,3794,NaN,2939,NaN,NaN,250,NaN,1831,NaN,NaN,872,NaN,NaN,NaN,921,NaN,9975,( 1),NaN,358,(209),NaN,20
36,NaN,21,住吉,住吉,NaN,42115,(11),NaN,27361,NaN,NaN,12211,NaN,NaN,15150,NaN,NaN,2795,NaN,NaN,537,NaN,NaN,2239,NaN,19,NaN,NaN,138,NaN,363,NaN,NaN,445,NaN,NaN,NaN,1030,NaN,9914,( 1),NaN,69,(10),NaN,21
37,NaN,22,東住吉,東住吉,NaN,43175,(297),NaN,25451,NaN,NaN,11662,NaN,NaN,13789,NaN,NaN,4458,NaN,NaN,1031,NaN,NaN,3399,NaN,28,NaN,NaN,27,NaN,755,NaN,NaN,122,NaN,NaN,NaN,1038,NaN,10752,( 2),NaN,572,(295),NaN,22
38,NaN,23,平野,平野,NaN,72856,(137),NaN,42442,NaN,NaN,18649,NaN,NaN,23793,NaN,NaN,8013,NaN,NaN,1989,NaN,NaN,5927,NaN,97,NaN,NaN,170,NaN,1054,NaN,NaN,109,NaN,NaN,NaN,1453,NaN,19123,NaN,NaN,492,(137),NaN,23
39,NaN,24,西成,西成,NaN,28228,(23),NaN,15070,NaN,NaN,6853,NaN,NaN,8217,NaN,NaN,4065,NaN,NaN,1320,NaN,NaN,2700,NaN,45,NaN,NaN,54,NaN,762,NaN,NaN,97,NaN,NaN,NaN,657,NaN,7353,NaN,NaN,170,(23),NaN,24

In [170]:
for i in df.keys():
    print(i)

H29
H28
H27
H26
H25
H24
H23
H22
H21
H20
H19
H18
H17
H16
H15
H14

In [38]:
# 年度のエクセルファイルから必要部分だけ切り出す
def seikei(df):
    df = df.copy()
    df = df.iloc[10:40 , [1, 2, 5, 6, 8, 11, 14, 17, 20, 23, 25, 28, 30, 31, 33, 34, 37, 40, 41, 43, 44]]
    return df

# 全体情報と地域情報に分離する
def bunri(df):
    df_all = df.iloc[:5, :]
    df_area = df.iloc[6:, :]
    return df_all, df_area

# 全体情報を整理する。まずは除去と置き換え
def remove_n_replace1(df):
    df.iloc[0, 0] = df.iloc[0, 0].replace('平　成　', '')
    df = df.T.dropna()
    df = df.T
    print(df)
    # カッコ、カンマ、マイナスを取り除く
    problem_col = [2, 17, 19]
    for i in range(len(df)):
        for i2 in problem_col:
            df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(',', '')
            df.iloc[i, i2] = int(df.iloc[i, i2])
            if df.iloc[i, i2] < 0:
                df.iloc[i, i2] = df.iloc[i, i2] * -1
    return df

# H23以前
def remove_n_replace2(df):
    df.iloc[0, 0] = df.iloc[0, 0].replace('平　成　', '')
    df = df.T.dropna()
    df = df.T
    print(df)
    # カッコ、カンマ、マイナスを取り除く
    problem_col = [2, 15, 17]
    for i in range(len(df)):
        for i2 in problem_col:
            df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(',', '')
            df.iloc[i, i2] = int(df.iloc[i, i2])
            if df.iloc[i, i2] < 0:
                df.iloc[i, i2] = df.iloc[i, i2] * -1
    return df

# 平成を西暦に(データフレーム用)
def heiseireki(df):
    for i in range(len(df)):
        if len(str(df.iloc[i, 0])) == 2:
            df.iloc[i, 0] = int(df.iloc[i, 0]) + 1988
        else:
            pass
    return df

# 平成を西暦に（単独用）
def heiseireki_alone(year):
    year = int(year.replace('H', ''))
    year = year + 1988
    return year

def zentai1(df, column_name):
    df = remove_n_replace1(df)
    df = heiseireki(df)
    df.columns = column_name
    return df

def zentai2(df, column_name):
    df = remove_n_replace2(df)
    df = heiseireki(df)
    df.columns = column_name
    return df    

# 地域データカッコなど処理
def remove_area1(df):
    problem_col= [2, 17, 19]
    for i in range(len(df)):
        for i2 in problem_col:
            df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(',', '')
            df.iloc[i, i2] = int(df.iloc[i, i2])
            if df.iloc[i, i2] < 0:
                df.iloc[i, i2] = df.iloc[i, i2] * -1
            elif df.iloc[i, i2] == 'NaN':
                df.iloc[i, i2] = 0
            else:
                pass
    return df

def remove_area2(df):
    problem_col= [2, 15, 17]
    for i in range(len(df)):
        for i2 in problem_col:
            df.iloc[i, i2] = str(df.iloc[i, i2]).replace('(', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(')', '')
            df.iloc[i, i2] = df.iloc[i, i2].replace(',', '')
            df.iloc[i, i2] = int(df.iloc[i, i2])
            if df.iloc[i, i2] < 0:
                df.iloc[i, i2] = df.iloc[i, i2] * -1
            elif df.iloc[i, i2] == 'NaN':
                df.iloc[i, i2] = 0
            else:
                pass
    return df

# 地域データの整頓
def area_betsu1(df, year, column_name):
    df = df.iloc[:, 1:]
    df = remove_area1(df)
    df.columns = column_name
    df['年度'] = year
    df.index = [i for i in range(len(df))]
    return df

def area_betsu2(df, year, column_name):
    df = df.iloc[:, 1:]
    df = remove_area2(df)
    df.columns = column_name
    df['年度'] = year
    df.index = [i for i in range(len(df))]
    return df

In [39]:
def zensyori(df):
    df_all = pd.DataFrame()
    df_area = pd.DataFrame()
    for i in df.keys():
        year1 = heiseireki_alone(i)
        osaka_car = ['総数', '電気自動車総数', '乗用車総数', '普通乗用車', '小型乗用車', '貨物車総数', '貨物普通車', '貨物小型車', '貨物被牽引車',
            'バス', '特種特殊総数', '普通特種', '小型特種', '大型特種', '小型二輪', '軽自動車', '電気軽自動車', '小型特殊自動車', '電気小型特殊自動車']
        osaka_car1 = osaka_car.copy()
        osaka_car2 = osaka_car.copy()
        osaka_car1.insert(0, '年度')
        osaka_car2.insert(0, '地域')
        
        if year1 > 2011:
            df1 = df[i]
            df1 = seikei(df1)
            df_all_1, df_area_1 = bunri(df1)
            df_all_1 = zentai1(df_all_1, osaka_car1)
            df_area_1 = area_betsu1(df_area_1, year1, osaka_car2)
        
            df_all = pd.concat([df_all, df_all_1], axis=1)
            df_area = pd.concat([df_area, df_area_1], axis=1)
            
        else:
            df1 = df[i]
            df1 = seikei(df1)
            df_all_1, df_area_1 = bunri(df1)
            df_all_1 = zentai2(df_all_1, osaka_car1)
            df_area_1 = area_betsu2(df_area_1, year1, osaka_car2)
        
            df_all = pd.concat([df_all, df_all_1], axis=1)
            df_area = pd.concat([df_area, df_area_1], axis=1)
                        
    return df_all, df_area

In [40]:
dfa, dfa2 = zensyori(df)

C:\Users\hogaw\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\hogaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\hogaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:81: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\hogaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\hogaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:83: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\hogaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

   Unnamed: 1 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11 Unnamed: 14  \
10         24     835576    (3,110)     478560      230215      248345
11         25     838591    (3,146)     477502      234207      243295
12         26     842716    (3,268)     475085      235892      239193
13         27     841066       3341     475260      239448      235812
14         28     845427       3366     477819      244678      233141

   Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28 Unnamed: 30  \
10      110288       30128       74634        5526        2070       20682
11      109766       30440       73678        5648        1998       20950
12      109121       30950       72530        5641        1994       21248
13      108659       31281       71610        5768        2072       21660
14      108409       31530       70967        5912        2146       22025

   Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40 Unnamed: 41  \
10       12865        2522        5295       22742      194300       (200)
11       13148        2494        5308       22837      198708       (209)
12       13394        2555        5299       22188      206212       (222)
13       13742        2628        5290       22822      203718       (215)
14       14102        2653        5270       22805      205382        -206

   Unnamed: 43 Unnamed: 44
10        6934     (2,910)
11        6830     (2,937)
12        6868     (3,046)
13        6875     (3,126)
14        6841       -3160
   Unnamed: 1 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11 Unnamed: 14  \
10         23     834729    (2,990)     480418      227746      252672
11         24     835576    (3,110)     478560      230215      248345
12         25     838591    (3,146)     477502      234207      243295
13         26     842716    (3,268)     475085      235892      239193
14         27     841066       3341     475260      239448      235812

   Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28 Unnamed: 30  \
10      112385       30335       76516        5534        2143       20514
11      110288       30128       74634        5526        2070       20682
12      109766       30440       73678        5648        1998       20950
13      109121       30950       72530        5641        1994       21248
14      108659       31281       71610        5768        2072       21660

   Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40 Unnamed: 41  \
10       12749        2471        5294       20679      191418        (92)
11       12865        2522        5295       22742      194300       (200)
12       13148        2494        5308       22837      198708       (209)
13       13394        2555        5299       22188      206212       (222)
14       13742        2628        5290       22822      203718       (215)

   Unnamed: 43 Unnamed: 44
10        7172     (2,898)
11        6934     (2,910)
12        6830     (2,937)
13        6868     (3,046)
14        6875     (3,126)
   Unnamed: 1 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11 Unnamed: 14  \
10         22     839638    (2,944)     482203      225228      256975
11         23     834729    (2,990)     480418      227746      252672
12         24     833298      -3110     478560      230215      248345
13         25     836288    (3,146)     477502      234207      243295
14         26     841924    (3,268)     475085      235892      239193

   Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28 Unnamed: 30  \
10      114317       30635       78236        5446        2071       20411
11      112385       30335       76516        5534        2143       20514
12      110288       30128       74634        5526        2070       20682
13      109766       30440       73678        5648        1998       20950
14      109121       30950       72530        5641        1994       21248

   Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40 Unnamed: 41  \
10       12592        2504        5315       21106      192173        (52)
11       12749        2471        5294       20679      191418        (92)
12       12865        2522        5295       20464      194300       (200)
13       13148        2494        5308       20534      198708       (209)
14       13394        2555        5299       21396      206212       (222)

   Unnamed: 43 Unnamed: 44
10        7357     (2,892)
11        7172     (2,898)
12        6934       -2910
13        6830     (2,937)
14        6868     (3,046)
   Unnamed: 1 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11 Unnamed: 14  \
10    平 成  21     848705    (2,956)     487518      223916      263602
11         22     839638    (2,944)     482203      225228      256975
12         23     834729    (2,990)     480418      227746      252672
13         24     833298      -3110     478560      230215      248345
14         25     836288    (3,146)     477502      234207      243295

   Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28 Unnamed: 30  \
10      116947       30977       80570        5400        2171       20755
11      114317       30635       78236        5446        2071       20411
12      112385       30335       76516        5534        2143       20514
13      110288       30128       74634        5526        2070       20682
14      109766       30440       73678        5648        1998       20950

   Unnamed: 31 Unnamed: 33 Unnamed: 34 Unnamed: 37 Unnamed: 40 Unnamed: 41  \
10       12808        2550        5397       21193      192737        (52)
11       12592        2504        5315       21106      192173        (52)
12       12749        2471        5294       20679      191418        (92)
13       12865        2522        5295       20464      194300       (200)
14       13148        2494        5308       20534      198708       (209)

   Unnamed: 43 Unnamed: 44
10        7384     (2,904)
11        7357     (2,892)
12        7172     (2,898)
13        6934       -2910
14        6830     (2,937)
   Unnamed: 1 Unnamed: 5 Unnamed: 6 Unnamed: 8 Unnamed: 11 Unnamed: 14  \
10    平 成  20     863396    (2,868)     498570      228472      270098
11         21     848705    (2,956)     487518      223916      263602
12         22     837134    (2,944)     482203      225228      256975
13         23     834729    (2,990)     480418      227746      252672
14         24     835576      -3110     478560      230215      248345

   Unnamed: 17 Unnamed: 20 Unnamed: 23 Unnamed: 25 Unnamed: 28 Unnamed: 30  \
10      120348       31474       83334        5540        2220       20607
11      116947       30977       80570        5400        2171       20755
12      114317       30635       78236        5446        2071       20411
13      112385       30335       76516        5534        2143       20514
14      110288       30128       74634        5526        2070       20682

   Unnamed: 31 Unnamed: 33 Unnamed: 40 Unnamed: 43
10       12749        5381        (15)     (2,853)
11       12808        5397        (52)     (2,904)
12       12592        5315        (52)     (2,892)
13       12749        5294        (92)     (2,898)
14       12865        5295       (200)       -2910

C:\Users\hogaw\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

IndexError: single positional indexer is out-of-bounds

In [123]:
for i in df.keys():
    print(df[i].head())

  184　運輸・通信 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0       NaN        NaN        NaN        NaN         NaN        NaN
1       NaN        NaN        NaN        NaN         NaN        NaN
2       NaN        NaN        NaN        NaN         NaN        NaN
3       NaN        NaN        NaN        NaN         NaN        NaN
4       NaN        NaN        NaN        NaN         NaN        NaN

  Unnamed: 6  Unnamed: 7 Unnamed: 8 Unnamed: 9  Unnamed: 10 Unnamed: 11  \
0        NaN         NaN        NaN        NaN          NaN         NaN
1        NaN         NaN        NaN        NaN          NaN         NaN
2        NaN         NaN        NaN        NaN          NaN         NaN
3        NaN         NaN        NaN        NaN          NaN         NaN
4        NaN         NaN        NaN        NaN          NaN         NaN

   Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16 Unnamed: 17  \
0          NaN         NaN         NaN         NaN          NaN         NaN
1          NaN         NaN         NaN         NaN          NaN         NaN
2          NaN         NaN         NaN         NaN          NaN         NaN
3          NaN         NaN         NaN         NaN          NaN         NaN
4          NaN         NaN         NaN         NaN          NaN         NaN

  Unnamed: 18  Unnamed: 19 Unnamed: 20 Unnamed: 21  Unnamed: 22  \
0         NaN          NaN         NaN         NaN          NaN
1         NaN          NaN         NaN         NaN          NaN
2         NaN          NaN         NaN         NaN          NaN
3         NaN          NaN         NaN         NaN          NaN
4         NaN          NaN         NaN         NaN          NaN

              Unnamed: 23  Unnamed: 24        Unnamed: 25 Unnamed: 26  \
0                     NaN          NaN                NaN         NaN
1  11－１　自　  　動 　　 車 　 　の           NaN  　保 　 　有 　　　台　 　　数         NaN
2                     NaN          NaN                NaN         NaN
3           その1　自 動 車 及 び          NaN        　軽  自  動  車         NaN
4                     NaN          NaN                NaN         NaN

   Unnamed: 27 Unnamed: 28  Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  \
0          NaN         NaN          NaN         NaN         NaN         NaN
1          NaN         NaN          NaN         NaN         NaN         NaN
2          NaN         NaN          NaN         NaN         NaN         NaN
3          NaN         NaN          NaN         NaN         NaN         NaN
4          NaN         NaN          NaN         NaN         NaN         NaN

  Unnamed: 33 Unnamed: 34 Unnamed: 35  Unnamed: 36 Unnamed: 37 Unnamed: 38  \
0         NaN         NaN         NaN          NaN         NaN         NaN
1         NaN         NaN         NaN          NaN         NaN         NaN
2         NaN         NaN         NaN          NaN         NaN         NaN
3         NaN         NaN         NaN          NaN         NaN         NaN
4         NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 39 Unnamed: 40 Unnamed: 41  Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0          NaN         NaN         NaN          NaN         NaN         NaN
1          NaN         NaN         NaN          NaN         NaN         NaN
2          NaN         NaN         NaN          NaN         NaN         NaN
3          NaN         NaN         NaN          NaN         NaN         NaN
4          NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 45 運輸・通信　185
0          NaN       NaN
1          NaN       NaN
2          NaN       NaN
3          NaN       NaN
4          NaN       NaN
  170　運輸・通信 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0       NaN        NaN        NaN        NaN         NaN        NaN
1       NaN        NaN        NaN        NaN         NaN        NaN
2       NaN        NaN        NaN        NaN         NaN        NaN
3       NaN        NaN        NaN        NaN         NaN        NaN
4       NaN        NaN        NaN        NaN         NaN        NaN

  Unnamed: 6  Unnamed: 7 Unnamed: 8 Unnamed: 9  Unnamed: 10 Unnamed: 11  \
0        NaN         NaN        NaN        NaN          NaN         NaN
1        NaN         NaN        NaN        NaN          NaN         NaN
2        NaN         NaN        NaN        NaN          NaN         NaN
3        NaN         NaN        NaN        NaN          NaN         NaN
4        NaN         NaN        NaN        NaN          NaN         NaN

   Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16 Unnamed: 17  \
0          NaN         NaN         NaN         NaN          NaN         NaN
1          NaN         NaN         NaN         NaN          NaN         NaN
2          NaN         NaN         NaN         NaN          NaN         NaN
3          NaN         NaN         NaN         NaN          NaN         NaN
4          NaN         NaN         NaN         NaN          NaN         NaN

  Unnamed: 18  Unnamed: 19 Unnamed: 20 Unnamed: 21  Unnamed: 22  \
0         NaN          NaN         NaN         NaN          NaN
1         NaN          NaN         NaN         NaN          NaN
2         NaN          NaN         NaN         NaN          NaN
3         NaN          NaN         NaN         NaN          NaN
4         NaN          NaN         NaN         NaN          NaN

              Unnamed: 23  Unnamed: 24        Unnamed: 25 Unnamed: 26  \
0                     NaN          NaN                NaN         NaN
1  11－１　自　  　動 　　 車 　 　の           NaN  　保 　 　有 　　　台　 　　数         NaN
2                     NaN          NaN                NaN         NaN
3           その1　自 動 車 及 び          NaN        　軽  自  動  車         NaN
4                     NaN          NaN                NaN         NaN

   Unnamed: 27 Unnamed: 28  Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  \
0          NaN         NaN          NaN         NaN         NaN         NaN
1          NaN         NaN          NaN         NaN         NaN         NaN
2          NaN         NaN          NaN         NaN         NaN         NaN
3          NaN         NaN          NaN         NaN         NaN         NaN
4          NaN         NaN          NaN         NaN         NaN         NaN

  Unnamed: 33 Unnamed: 34 Unnamed: 35  Unnamed: 36 Unnamed: 37 Unnamed: 38  \
0         NaN         NaN         NaN          NaN         NaN         NaN
1         NaN         NaN         NaN          NaN         NaN         NaN
2         NaN         NaN         NaN          NaN         NaN         NaN
3         NaN         NaN         NaN          NaN         NaN         NaN
4         NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 39 Unnamed: 40 Unnamed: 41  Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0          NaN         NaN         NaN          NaN         NaN         NaN
1          NaN         NaN         NaN          NaN         NaN         NaN
2          NaN         NaN         NaN          NaN         NaN         NaN
3          NaN         NaN         NaN          NaN         NaN         NaN
4          NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 45 運輸・通信　171
0          NaN       NaN
1          NaN       NaN
2          NaN       NaN
3          NaN       NaN
4          NaN       NaN
  140　運輸・通信 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0       NaN        NaN        NaN        NaN         NaN        NaN
1       NaN        NaN        NaN        NaN         NaN        NaN
2       NaN        NaN        NaN        NaN         NaN        NaN
3       NaN        NaN        NaN        NaN         NaN        NaN
4       NaN        NaN        NaN        NaN         NaN        NaN

  Unnamed: 6  Unnamed: 7 Unnamed: 8 Unnamed: 9  Unnamed: 10 Unnamed: 11  \
0        NaN         NaN        NaN        NaN          NaN         NaN
1        NaN         NaN        NaN        NaN          NaN         NaN
2        NaN         NaN        NaN        NaN          NaN         NaN
3        NaN         NaN        NaN        NaN          NaN         NaN
4        NaN         NaN        NaN        NaN          NaN         NaN

   Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16 Unnamed: 17  \
0          NaN         NaN         NaN         NaN          NaN         NaN
1          NaN         NaN         NaN         NaN          NaN         NaN
2          NaN         NaN         NaN         NaN          NaN         NaN
3          NaN         NaN         NaN         NaN          NaN         NaN
4          NaN         NaN         NaN         NaN          NaN         NaN

  Unnamed: 18  Unnamed: 19 Unnamed: 20 Unnamed: 21  Unnamed: 22  \
0         NaN          NaN         NaN         NaN          NaN
1         NaN          NaN         NaN         NaN          NaN
2         NaN          NaN         NaN         NaN          NaN
3         NaN          NaN         NaN         NaN          NaN
4         NaN          NaN         NaN         NaN          NaN

              Unnamed: 23  Unnamed: 24        Unnamed: 25 Unnamed: 26  \
0                     NaN          NaN                NaN         NaN
1  11－１　自　  　動 　　 車 　 　の           NaN  　保 　 　有 　　　台　 　　数         NaN
2                     NaN          NaN                NaN         NaN
3           その1　自 動 車 及 び          NaN        　軽  自  動  車         NaN
4                     NaN          NaN                NaN         NaN

   Unnamed: 27 Unnamed: 28  Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  \
0          NaN         NaN          NaN         NaN         NaN         NaN
1          NaN         NaN          NaN         NaN         NaN         NaN
2          NaN         NaN          NaN         NaN         NaN         NaN
3          NaN         NaN          NaN         NaN         NaN         NaN
4          NaN         NaN          NaN         NaN         NaN         NaN

  Unnamed: 33 Unnamed: 34 Unnamed: 35  Unnamed: 36 Unnamed: 37 Unnamed: 38  \
0         NaN         NaN         NaN          NaN         NaN         NaN
1         NaN         NaN         NaN          NaN         NaN         NaN
2         NaN         NaN         NaN          NaN         NaN         NaN
3         NaN         NaN         NaN          NaN         NaN         NaN
4         NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 39 Unnamed: 40 Unnamed: 41  Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0          NaN         NaN         NaN          NaN         NaN         NaN
1          NaN         NaN         NaN          NaN         NaN         NaN
2          NaN         NaN         NaN          NaN         NaN         NaN
3          NaN         NaN         NaN          NaN         NaN         NaN
4          NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 45 運輸・通信　141
0          NaN       NaN
1          NaN       NaN
2          NaN       NaN
3          NaN       NaN
4          NaN       NaN
  120　運輸・通信 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0       NaN        NaN        NaN        NaN         NaN        NaN
1       NaN        NaN        NaN        NaN         NaN        NaN
2       NaN        NaN        NaN        NaN         NaN        NaN
3       NaN        NaN        NaN        NaN         NaN        NaN
4       NaN        NaN        NaN        NaN         NaN        NaN

  Unnamed: 6  Unnamed: 7 Unnamed: 8  Unnamed: 9  Unnamed: 10 Unnamed: 11  \
0        NaN         NaN        NaN         NaN          NaN         NaN
1        NaN         NaN        NaN         NaN          NaN         NaN
2        NaN         NaN        NaN         NaN          NaN         NaN
3        NaN         NaN        NaN         NaN          NaN         NaN
4        NaN         NaN        NaN         NaN          NaN         NaN

   Unnamed: 12  Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16 Unnamed: 17  \
0          NaN          NaN         NaN         NaN          NaN         NaN
1          NaN          NaN         NaN         NaN          NaN         NaN
2          NaN          NaN         NaN         NaN          NaN         NaN
3          NaN          NaN         NaN         NaN          NaN         NaN
4          NaN          NaN         NaN         NaN          NaN         NaN

  Unnamed: 18  Unnamed: 19 Unnamed: 20 Unnamed: 21  Unnamed: 22  \
0         NaN          NaN         NaN         NaN          NaN
1         NaN          NaN         NaN         NaN          NaN
2         NaN          NaN         NaN         NaN          NaN
3         NaN          NaN         NaN         NaN          NaN
4         NaN          NaN         NaN         NaN          NaN

              Unnamed: 23  Unnamed: 24        Unnamed: 25 Unnamed: 26  \
0                     NaN          NaN                NaN         NaN
1  11－１　自　  　動 　　 車 　 　の           NaN  　保 　 　有 　　　台　 　　数         NaN
2                     NaN          NaN                NaN         NaN
3           その1　自 動 車 及 び          NaN        　軽  自  動  車         NaN
4                     NaN          NaN                NaN         NaN

   Unnamed: 27 Unnamed: 28  Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  \
0          NaN         NaN          NaN         NaN         NaN         NaN
1          NaN         NaN          NaN         NaN         NaN         NaN
2          NaN         NaN          NaN         NaN         NaN         NaN
3          NaN         NaN          NaN         NaN         NaN         NaN
4          NaN         NaN          NaN         NaN         NaN         NaN

  Unnamed: 33 Unnamed: 34 Unnamed: 35  Unnamed: 36 Unnamed: 37 Unnamed: 38  \
0         NaN         NaN         NaN          NaN         NaN         NaN
1         NaN         NaN         NaN          NaN         NaN         NaN
2         NaN         NaN         NaN          NaN         NaN         NaN
3         NaN         NaN         NaN          NaN         NaN         NaN
4         NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 39 Unnamed: 40 Unnamed: 41  Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0          NaN         NaN         NaN          NaN         NaN         NaN
1          NaN         NaN         NaN          NaN         NaN         NaN
2          NaN         NaN         NaN          NaN         NaN         NaN
3          NaN         NaN         NaN          NaN         NaN         NaN
4          NaN         NaN         NaN          NaN         NaN         NaN

   Unnamed: 45 運輸・通信　121
0          NaN       NaN
1          NaN       NaN
2          NaN       NaN
3          NaN       NaN
4          NaN       NaN
                                     178　運輸・通信 Unnamed: 1 Unnamed: 2  \
0                                          NaN        NaN        NaN
1  11－１　　　自　  　動　  　車　  　の　  　保　  　有　  　台　  　数        NaN        NaN
2                                          NaN        NaN        NaN
3               その1　　自 　動 　車 　及 　び 　軽 　自 　動 　車        NaN        NaN
4                                          NaN        NaN        NaN

  Unnamed: 3  Unnamed: 4 Unnamed: 5 Unnamed: 6  Unnamed: 7 Unnamed: 8  \
0        NaN         NaN        NaN        NaN         NaN        NaN
1        NaN         NaN        NaN        NaN         NaN        NaN
2        NaN         NaN        NaN        NaN         NaN        NaN
3        NaN         NaN        NaN        NaN         NaN        NaN
4        NaN         NaN        NaN        NaN         NaN        NaN

   Unnamed: 9  Unnamed: 10 Unnamed: 11  Unnamed: 12  Unnamed: 13 Unnamed: 14  \
0         NaN          NaN         NaN          NaN          NaN         NaN
1         NaN          NaN         NaN          NaN          NaN         NaN
2         NaN          NaN         NaN          NaN          NaN         NaN
3         NaN          NaN         NaN          NaN          NaN         NaN
4         NaN          NaN         NaN          NaN          NaN         NaN

  Unnamed: 15  Unnamed: 16 Unnamed: 17 Unnamed: 18  Unnamed: 19 Unnamed: 20  \
0         NaN          NaN         NaN         NaN          NaN         NaN
1         NaN          NaN         NaN         NaN          NaN         NaN
2         NaN          NaN         NaN         NaN          NaN         NaN
3         NaN          NaN         NaN         NaN          NaN         NaN
4         NaN          NaN         NaN         NaN          NaN         NaN

  Unnamed: 21  Unnamed: 22 Unnamed: 23  Unnamed: 24 Unnamed: 25 Unnamed: 26  \
0         NaN          NaN         NaN          NaN         NaN         NaN
1         NaN          NaN         NaN          NaN         NaN         NaN
2         NaN          NaN         NaN          NaN         NaN         NaN
3         NaN          NaN         NaN          NaN         NaN         NaN
4         NaN          NaN         NaN          NaN         NaN         NaN

   Unnamed: 27 Unnamed: 28  Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32  \
0          NaN         NaN          NaN         NaN         NaN         NaN
1          NaN         NaN          NaN         NaN         NaN         NaN
2          NaN         NaN          NaN         NaN         NaN         NaN
3          NaN         NaN          NaN         NaN         NaN         NaN
4          NaN         NaN          NaN         NaN         NaN         NaN

  Unnamed: 33 Unnamed: 34  Unnamed: 35 Unnamed: 36 Unnamed: 37  Unnamed: 38  \
0         NaN         NaN          NaN         NaN         NaN          NaN
1         NaN         NaN          NaN         NaN         NaN          NaN
2         NaN         NaN          NaN         NaN         NaN          NaN
3         NaN         NaN          NaN         NaN         NaN          NaN
4         NaN         NaN          NaN         NaN         NaN          NaN

  Unnamed: 39 Unnamed: 40  Unnamed: 41 Unnamed: 42 Unnamed: 43  Unnamed: 44  \
0         NaN         NaN          NaN         NaN         NaN          NaN
1         NaN         NaN          NaN         NaN         NaN          NaN
2         NaN         NaN          NaN         NaN         NaN          NaN
3         NaN         NaN          NaN         NaN         NaN          NaN
4         NaN         NaN          NaN         NaN         NaN          NaN

  運輸・通信　179
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
                                    134　運輸・通信 Unnamed: 1 Unnamed: 2  \
0                                         NaN        NaN        NaN
1  11－１　自　  　動 　　 車 　 　の   　保 　 　有 　　　台　 　　数         NaN        NaN
2                                         NaN        NaN        NaN
3                    その1　自 動 車 及 び　軽  自  動  車        NaN        NaN
4                                         NaN        NaN        NaN

  Unnamed: 3  Unnamed: 4 Unnamed: 5 Unnamed: 6  Unnamed: 7 Unnamed: 8  \
0        NaN         NaN        NaN        NaN         NaN        NaN
1        NaN         NaN        NaN        NaN         NaN        NaN
2        NaN         NaN        NaN        NaN         NaN        NaN
3        NaN         NaN        NaN        NaN         NaN        NaN
4        NaN         NaN        NaN        NaN         NaN        NaN

   Unnamed: 9  Unnamed: 10 Unnamed: 11  Unnamed: 12  Unnamed: 13 Unnamed: 14  \
0         NaN          NaN         NaN          NaN          NaN         NaN
1         NaN          NaN         NaN          NaN          NaN         NaN
2         NaN          NaN         NaN          NaN          NaN         NaN
3         NaN          NaN         NaN          NaN          NaN         NaN
4         NaN          NaN         NaN          NaN          NaN         NaN

  Unnamed: 15  Unnamed: 16 Unnamed: 17 Unnamed: 18  Unnamed: 19 Unnamed: 20  \
0         NaN          NaN         NaN         NaN          NaN         NaN
1         NaN          NaN         NaN         NaN          NaN         NaN
2         NaN          NaN         NaN         NaN          NaN         NaN
3         NaN          NaN         NaN         NaN          NaN         NaN

In [127]:
df = seikei(df['H28'])

In [128]:
df

,Unnamed: 1,Unnamed: 2,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 11,Unnamed: 14,Unnamed: 17,Unnamed: 20,Unnamed: 23,Unnamed: 25,Unnamed: 28,Unnamed: 30,Unnamed: 31,Unnamed: 33,Unnamed: 34,Unnamed: 37,Unnamed: 40,Unnamed: 41,Unnamed: 43,Unnamed: 44
10,平 成 23,NaN,834729,"(2,990)",480418,227746,252672,112385,30335,76516,5534,2143,20514,12749,2471,5294,20679,191418,(92),7172,"(2,898)"
11,24,NaN,835576,"(3,110)",478560,230215,248345,110288,30128,74634,5526,2070,20682,12865,2522,5295,22742,194300,(200),6934,"(2,910)"
12,25,NaN,838591,"(3,146)",477502,234207,243295,109766,30440,73678,5648,1998,20950,13148,2494,5308,22837,198708,(209),6830,"(2,937)"
13,26,NaN,842716,"(3,268)",475085,235892,239193,109121,30950,72530,5641,1994,21248,13394,2555,5299,22188,206212,(222),6868,"(3,046)"
14,27,NaN,841066,3341,475260,239448,235812,108659,31281,71610,5768,2072,21660,13742,2628,5290,22822,203718,(215),6875,"(3,126)"
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,１,北,41615,131,25301,13096,12205,6402,851,5539,12,225,664,385,123,156,986,7784,18,253,113
17,２,都島,24827,45,15681,8437,7244,2331,588,1741,2,25,370,204,98,68,807,5535,2,78,43
18,３,福島,21821,878,11638,6532,5106,3074,749,2292,33,13,511,307,122,82,546,4587,7,1452,871
19,４,此花,24754,103,11505,5749,5756,4762,2144,2126,492,284,1635,1282,53,300,694,5637,5,237,98
20,５,中央,45269,65,29363,14500,14863,6452,408,6032,12,37,499,227,92,180,1070,7729,12,119,53
21,６,西,34231,190,19930,10307,9623,6234,932,5129,173,17,666,349,69,248,794,6210,35,380,155
22,７,港,27721,121,12946,6708,6238,5378,2316,2480,582,196,1741,862,44,835,689,6466,9,305,112
23,８,大正,26354,59,12132,5921,6211,5352,2428,2468,456,146,1120,688,53,379,612,6740,5,252,54
24,９,天王寺,17432,42,11454,7123,4331,1542,180,1359,3,15,198,118,49,31,431,3691,2,101,40
25,10,浪速,19188,76,9821,5182,4639,3101,686,2404,11,21,914,383,348,183,517,4615,9,199,67
26,11,西淀川,38080,124,19636,9810,9826,6899,2881,3768,250,102,1620,1151,79,390,980,8472,10,371,114
27,12,淀川,54902,109,34034,15642,18392,6615,1035,5570,10,88,556,421,96,39,1715,11703,18,191,91
28,13,東淀川,46766,74,26901,12887,14014,3935,1044,2889,2,127,962,702,64,196,1694,13035,6,112,68
29,14,東成,23302,113,13036,6613,6423,2986,749,2217,20,10,389,222,112,55,658,5954,3,269,110
30,15,生野,37553,161,20249,10058,10191,3766,806,2955,5,72,687,504,91,92,928,11395,3,456,158
31,16,旭,23866,22,14121,6955,7166,1762,365,1388,9,38,480,377,50,53,840,6564,5,61,17
32,17,城東,44278,102,26777,13541,13236,3857,934,2909,14,33,845,509,120,216,1531,11001,3,234,99
33,18,鶴見,37361,83,21156,10765,10391,4099,1739,2338,22,35,774,498,121,155,1051,9982,10,264,73
34,19,阿倍野,24550,12,16823,9446,7377,1293,195,1097,1,15,234,173,42,19,749,5390,6,46,6
35,20,住之江,51898,280,24190,11446,12744,12136,5353,3292,3491,257,3001,2013,145,843,1041,10911,17,362,263
36,21,住吉,39293,22,24541,12233,12308,2243,493,1735,15,135,789,274,73,442,1093,10434,6,58,16
37,22,東住吉,40905,281,23137,11616,11521,3727,999,2678,50,71,938,560,264,114,1085,11537,9,410,272
38,23,平野,69758,214,38093,18596,19497,7235,2121,5056,58,64,1308,1015,180,113,1657,20903,12,498,202
39,24,西成,25342,34,12795,6285,6510,3478,1285,2148,45,46,759,518,140,101,654,7443,3,167,31