In [1]:
import pandas as pd

In [4]:
pd.set_option('max_columns', 50)
pd.set_option('max_row', 50)
excel = pd.ExcelFile('osaka_car.xls')

In [6]:
len(excel.sheet_names)

16

In [7]:
df = pd.read_excel('osaka_car.xls', sheet_name=excel.sheet_names)

In [12]:
dfh13 = df['H14'].iloc[10:40, :]
dfh13.columns = [i for i in range(len(dfh13.columns))]
dfh13_1 = dfh13.iloc[:5, :]
dfh13_2 = dfh13.iloc[6:, :]

In [13]:
dfh13_1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45
10,NaN,平成９,NaN,年,NaN,945839,-2591.0,NaN,549522,NaN,NaN,186374,NaN,NaN,363148,NaN,NaN,180320,NaN,NaN,43376,NaN,NaN,132292,NaN,4652,NaN,NaN,2835,NaN,18416,NaN,NaN,5833,NaN,NaN,20384,NaN,NaN,160238,-90.0,NaN,8291,-2501.0,NaN,９
11,NaN,NaN,10,年,NaN,931917,-2633.0,NaN,548197,NaN,NaN,195662,NaN,NaN,352535,NaN,NaN,169856,NaN,NaN,41913,NaN,NaN,123384,NaN,4559,NaN,NaN,2740,NaN,19033,NaN,NaN,5791,NaN,NaN,20222,NaN,NaN,157838,-91.0,NaN,8240,-2542.0,NaN,10
12,NaN,NaN,11,年,NaN,921544,-2748.0,NaN,543083,NaN,NaN,203759,NaN,NaN,339324,NaN,NaN,163018,NaN,NaN,39669,NaN,NaN,118858,NaN,4491,NaN,NaN,2683,NaN,19295,NaN,NaN,5711,NaN,NaN,20154,NaN,NaN,159341,-95.0,NaN,8259,-2653.0,NaN,11
13,NaN,NaN,12,年,NaN,917210,-2789.0,NaN,539770,NaN,NaN,210901,NaN,NaN,328869,NaN,NaN,158380,NaN,NaN,39142,NaN,NaN,114631,NaN,4607,NaN,NaN,2637,NaN,19560,NaN,NaN,5669,NaN,NaN,20426,NaN,NaN,162574,-101.0,NaN,8194,-2688.0,NaN,12
14,NaN,NaN,13,年,NaN,913052,-2753.0,NaN,537677,NaN,NaN,216334,NaN,NaN,321343,NaN,NaN,153369,NaN,NaN,38250,NaN,NaN,110497,NaN,4622,NaN,NaN,2479,NaN,19813,NaN,NaN,5604,NaN,NaN,20827,NaN,NaN,165220,-88.0,NaN,8063,-2665.0,NaN,13

In [14]:
dfh13_2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45
16,NaN,１,北,NaN,NaN,44823,-94.0,NaN,25122,NaN,NaN,9760,NaN,NaN,15362,NaN,NaN,10609,NaN,NaN,1425,NaN,NaN,9108,NaN,76,NaN,NaN,191,NaN,652,NaN,NaN,159,NaN,NaN,859,NaN,NaN,6883,-6.0,NaN,348,-88.0,NaN,１
17,NaN,２,都島,都島,NaN,26880,-59.0,NaN,17110,NaN,NaN,7231,NaN,NaN,9879,NaN,NaN,3837,NaN,NaN,867,NaN,NaN,2967,NaN,3,NaN,NaN,21,NaN,432,NaN,NaN,68,NaN,NaN,741,NaN,NaN,4524,-2.0,NaN,147,-57.0,NaN,２
18,NaN,３,福島,福島,NaN,23340,-923.0,NaN,11532,NaN,NaN,4831,NaN,NaN,6701,NaN,NaN,5203,NaN,NaN,1264,NaN,NaN,3901,NaN,38,NaN,NaN,34,NaN,556,NaN,NaN,83,NaN,NaN,451,NaN,NaN,3877,-1.0,NaN,1604,-922.0,NaN,３
19,NaN,４,此花,此花,NaN,24428,-6.0,NaN,12802,NaN,NaN,5190,NaN,NaN,7612,NaN,NaN,5088,NaN,NaN,2231,NaN,NaN,2611,NaN,246,NaN,NaN,207,NaN,1181,NaN,NaN,307,NaN,NaN,521,NaN,NaN,4190,-3.0,NaN,132,-3.0,NaN,４
20,NaN,５,中央,中央,NaN,44942,-81.0,NaN,27170,NaN,NaN,10228,NaN,NaN,16942,NaN,NaN,9658,NaN,NaN,677,NaN,NaN,8969,NaN,12,NaN,NaN,50,NaN,651,NaN,NaN,178,NaN,NaN,964,NaN,NaN,6061,-2.0,NaN,210,-79.0,NaN,５
21,NaN,６,西,西,NaN,35746,-138.0,NaN,18930,NaN,NaN,7658,NaN,NaN,11272,NaN,NaN,9584,NaN,NaN,1578,NaN,NaN,7679,NaN,327,NaN,NaN,34,NaN,560,NaN,NaN,268,NaN,NaN,599,NaN,NaN,5312,-11.0,NaN,459,-127.0,NaN,６
22,NaN,７,港,港,NaN,29765,-77.0,NaN,15141,NaN,NaN,6266,NaN,NaN,8875,NaN,NaN,6033,NaN,NaN,2129,NaN,NaN,3303,NaN,601,NaN,NaN,326,NaN,967,NaN,NaN,971,NaN,NaN,709,NaN,NaN,5330,-1.0,NaN,288,-76.0,NaN,７
23,NaN,８,大正,大正,NaN,29222,-26.0,NaN,15175,NaN,NaN,6053,NaN,NaN,9122,NaN,NaN,6424,NaN,NaN,2773,NaN,NaN,3116,NaN,535,NaN,NaN,112,NaN,797,NaN,NaN,349,NaN,NaN,557,NaN,NaN,5606,-1.0,NaN,202,-25.0,NaN,８
24,NaN,９,天王寺,天王寺,NaN,18957,-50.0,NaN,11792,NaN,NaN,5348,NaN,NaN,6444,NaN,NaN,2993,NaN,NaN,327,NaN,NaN,2666,NaN,-,NaN,NaN,18,NaN,173,NaN,NaN,31,NaN,NaN,479,NaN,NaN,3338,-3.0,NaN,133,-47.0,NaN,９
25,NaN,10,浪速,浪速,NaN,21714,-43.0,NaN,10562,NaN,NaN,4608,NaN,NaN,5954,NaN,NaN,4866,NaN,NaN,964,NaN,NaN,3887,NaN,15,NaN,NaN,13,NaN,832,NaN,NaN,202,NaN,NaN,407,NaN,NaN,4565,-1.0,NaN,267,-42.0,NaN,10
26,NaN,11,西淀川,西淀川,NaN,38077,-76.0,NaN,20938,NaN,NaN,8478,NaN,NaN,12460,NaN,NaN,8211,NaN,NaN,3329,NaN,NaN,4691,NaN,191,NaN,NaN,117,NaN,1279,NaN,NaN,407,NaN,NaN,785,NaN,NaN,5954,-3.0,NaN,386,-73.0,NaN,11
27,NaN,12,淀川,淀川,NaN,57294,-71.0,NaN,36019,NaN,NaN,13572,NaN,NaN,22447,NaN,NaN,9427,NaN,NaN,1419,NaN,NaN,7957,NaN,51,NaN,NaN,81,NaN,815,NaN,NaN,37,NaN,NaN,1473,NaN,NaN,9184,-2.0,NaN,258,-69.0,NaN,12
28,NaN,13,東淀川,東淀川,NaN,55004,-75.0,NaN,34642,NaN,NaN,13473,NaN,NaN,21169,NaN,NaN,6478,NaN,NaN,1687,NaN,NaN,4776,NaN,15,NaN,NaN,213,NaN,1177,NaN,NaN,209,NaN,NaN,1817,NaN,NaN,10287,-3.0,NaN,181,-72.0,NaN,13
29,NaN,14,東成,東成,NaN,26229,-106.0,NaN,15031,NaN,NaN,6228,NaN,NaN,8803,NaN,NaN,4607,NaN,NaN,979,NaN,NaN,3596,NaN,32,NaN,NaN,113,NaN,446,NaN,NaN,58,NaN,NaN,577,NaN,NaN,5015,-3.0,NaN,382,-103.0,NaN,14
30,NaN,15,生野,生野,NaN,44144,-119.0,NaN,25588,NaN,NaN,10253,NaN,NaN,15335,NaN,NaN,6024,NaN,NaN,1215,NaN,NaN,4805,NaN,4,NaN,NaN,65,NaN,690,NaN,NaN,107,NaN,NaN,940,NaN,NaN,10170,-2.0,NaN,560,-117.0,NaN,15
31,NaN,16,旭,旭,NaN,26961,-24.0,NaN,17261,NaN,NaN,6895,NaN,NaN,10366,NaN,NaN,2952,NaN,NaN,574,NaN,NaN,2372,NaN,6,NaN,NaN,36,NaN,358,NaN,NaN,40,NaN,NaN,824,NaN,NaN,5397,-2.0,NaN,93,-22.0,NaN,16
32,NaN,17,城東,城東,NaN,48170,-79.0,NaN,30155,NaN,NaN,11714,NaN,NaN,18441,NaN,NaN,6147,NaN,NaN,1369,NaN,NaN,4746,NaN,32,NaN,NaN,126,NaN,1240,NaN,NaN,220,NaN,NaN,1493,NaN,NaN,8465,-1.0,NaN,324,-78.0,NaN,17
33,NaN,18,鶴見,鶴見,NaN,38387,-73.0,NaN,23286,NaN,NaN,9416,NaN,NaN,13870,NaN,NaN,6241,NaN,NaN,2550,NaN,NaN,3652,NaN,39,NaN,NaN,76,NaN,836,NaN,NaN,166,NaN,NaN,830,NaN,NaN,6666,-1.0,NaN,286,-72.0,NaN,18
34,NaN,19,阿倍野,阿倍野,NaN,25624,-9.0,NaN,17570,NaN,NaN,7907,NaN,NaN,9663,NaN,NaN,2424,NaN,NaN,359,NaN,NaN,2063,NaN,2,NaN,NaN,25,NaN,305,NaN,NaN,19,NaN,NaN,722,NaN,NaN,4475,-1.0,NaN,84,-8.0,NaN,19
35,NaN,20,住之江,住之江,NaN,52609,-148.0,NaN,29176,NaN,NaN,11355,NaN,NaN,17821,NaN,NaN,10770,NaN,NaN,4093,NaN,NaN,4450,NaN,2227,NaN,NaN,197,NaN,2119,NaN,NaN,946,NaN,NaN,855,NaN,NaN,8227,-4.0,NaN,319,-144.0,NaN,20
36,NaN,21,住吉,住吉,NaN,45345,-8.0,NaN,30245,NaN,NaN,12465,NaN,NaN,17780,NaN,NaN,3996,NaN,NaN,724,NaN,NaN,3254,NaN,18,NaN,NaN,144,NaN,506,NaN,NaN,454,NaN,NaN,1079,NaN,NaN,8838,-1.0,NaN,83,-7.0,NaN,21
37,NaN,22,東住吉,東住吉,NaN,46972,-313.0,NaN,28058,NaN,NaN,11594,NaN,NaN,16464,NaN,NaN,6331,NaN,NaN,1502,NaN,NaN,4803,NaN,26,NaN,NaN,24,NaN,1026,NaN,NaN,123,NaN,NaN,1080,NaN,NaN,9716,-4.0,NaN,614,-309.0,NaN,22
38,NaN,23,平野,平野,NaN,77165,-106.0,NaN,47112,NaN,NaN,18947,NaN,NaN,28165,NaN,NaN,10188,NaN,NaN,2521,NaN,NaN,7630,NaN,37,NaN,NaN,178,NaN,1323,NaN,NaN,98,NaN,NaN,1405,NaN,NaN,16355,-1.0,NaN,506,-105.0,NaN,23
39,NaN,24,西成,西成,NaN,31254,-49.0,NaN,17260,NaN,NaN,6864,NaN,NaN,10396,NaN,NaN,5278,NaN,NaN,1694,NaN,NaN,3495,NaN,89,NaN,NaN,78,NaN,892,NaN,NaN,104,NaN,NaN,660,NaN,NaN,6785,-29.0,NaN,197,-20.0,NaN,24

In [197]:
def make_sheet(df, year):
    df1 = df[year].iloc[10:40,:]
    df1.columns = [i for i in range(len(df1.columns))]
    df1_1 = df1.iloc[:5, :]
    df1_2 = df1.iloc[6:, :]
    return df1_1, df1_2

def s26to29(df, df1):
    df = df.iloc[:,[1,2,5,6,8,11,14,17,20,23,25,28,30,31,33,34,37,40,41,43,44]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,31,33,34,37,40,41,43,44]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    print(df)
    print(df1)
    
def s24to25(df, df1):
    df = df.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,31,32,33,36,39,40,42,43]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,31,32,33,36,39,40,42,43]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    return df, df1
    
def s21to23(df,df1):
    df = df.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,36,39,40,42,43]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,36,39,40,42,43]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    return df, df1

def s20(df,df1):
    df = df.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,34,37,39,40,42,43]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,34,37,39,40,42,43]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    return df, df1 

def s19(df,df1):
    df = df.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,37,39,40,42,43]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,37,39,40,42,43]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    return df, df1 

def s15to18(df,df1):
    if df.isnull().iloc[4,36]:
        df.iloc[4,36] = df.iloc[4,37]
        if df.isnull().iloc[4,36]:
            df.iloc[4,36] = 0
    df = df.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,36,39,40,42,43]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,36,39,40,42,43]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    return df, df1 

# H14シートのみ
def s14(df,df1): 
    df14[0].iloc[1:5, 1] = df14[0].iloc[1:5, 2]
    df = df.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,36,39,40,42,43]]
    df = remove_nengo(df)
    df = df.T
    df = df.dropna().T
    df1 = df1.iloc[:, [1,2,5,6,8,11,14,17,20,23,25,28,30,33,36,39,40,42,43]]
    df1 = df1.iloc[:, 1:]
    print(len(df.columns))
    print(len(df1.columns))
    return df, df1     

# シートの1行目の平成を取り除く
def remove_nengo(df):
    df.iloc[0, 0] = df.iloc[0, 0].replace('平　成　', '')  # H29 - H27
    df.iloc[0, 0] = df.iloc[0, 0].replace('平 成  ', '') # H23 - H26
    df.iloc[0, 0] = df.iloc[0, 0].replace('平 成　', '') # H17 - H22
    df.iloc[0, 0] = df.iloc[0, 0].replace('平成', '') # H14 - H16
    return df

# 行、列に番号をふる
def number_count(df, df1):
    df.columns = [i for i in range(len(df.columns))]
    df.index = [i for i in range(len(df.index))]
    df1.columns = [i for i in range(len(df1.columns))]
    df1.index = [i for i in range(len(df1.index))]
    return df, df1

# 数値以外のデータを数値にする

In [195]:
def test_case(df, year):
    df,df1 = make_sheet(df, year)
    df, df1 = s14(df, df1)
    df, df1 = number_count(df, df1)
    print(df, df1)

In [196]:
test_case(df, 'H14')

18
18
   0       1     2       3       4       5       6      7       8     9   \
0  ９　  945839 -2591  549522  186374  363148  180320  43376  132292  4652
1  10  931917 -2633  548197  195662  352535  169856  41913  123384  4559
2  11  921544 -2748  543083  203759  339324  163018  39669  118858  4491
3  12  917210 -2789  539770  210901  328869  158380  39142  114631  4607
4  13  913052 -2753  537677  216334  321343  153369  38250  110497  4622

     10     11    12     13      14   15    16    17
0  2835  18416  5833  20384  160238  -90  8291 -2501
1  2740  19033  5791  20222  157838  -91  8240 -2542
2  2683  19295  5711  20154  159341  -95  8259 -2653
3  2637  19560  5669  20426  162574 -101  8194 -2688
4  2479  19813  5604  20827  165220  -88  8063 -2665        0      1      2      3      4      5      6     7     8     9    10  \
0     北  44823  -94.0  25122   9760  15362  10609  1425  9108    76  191
1    都島  26880  -59.0  17110   7231   9879   3837   867  2967     3   21
2    福島  23340 -923.0  11532   4831   6701   5203  1264  3901    38   34
3    此花  24428   -6.0  12802   5190   7612   5088  2231  2611   246  207
4    中央  44942  -81.0  27170  10228  16942   9658   677  8969    12   50
5     西  35746 -138.0  18930   7658  11272   9584  1578  7679   327   34
6     港  29765  -77.0  15141   6266   8875   6033  2129  3303   601  326
7    大正  29222  -26.0  15175   6053   9122   6424  2773  3116   535  112
8   天王寺  18957  -50.0  11792   5348   6444   2993   327  2666     -   18
9    浪速  21714  -43.0  10562   4608   5954   4866   964  3887    15   13
10  西淀川  38077  -76.0  20938   8478  12460   8211  3329  4691   191  117
11   淀川  57294  -71.0  36019  13572  22447   9427  1419  7957    51   81
12  東淀川  55004  -75.0  34642  13473  21169   6478  1687  4776    15  213
13   東成  26229 -106.0  15031   6228   8803   4607   979  3596    32  113
14   生野  44144 -119.0  25588  10253  15335   6024  1215  4805     4   65
15    旭  26961  -24.0  17261   6895  10366   2952   574  2372     6   36
16   城東  48170  -79.0  30155  11714  18441   6147  1369  4746    32  126
17   鶴見  38387  -73.0  23286   9416  13870   6241  2550  3652    39   76
18  阿倍野  25624   -9.0  17570   7907   9663   2424   359  2063     2   25
19  住之江  52609 -148.0  29176  11355  17821  10770  4093  4450  2227  197
20   住吉  45345   -8.0  30245  12465  17780   3996   724  3254    18  144
21  東住吉  46972 -313.0  28058  11594  16464   6331  1502  4803    26   24
22   平野  77165 -106.0  47112  18947  28165  10188  2521  7630    37  178
23   西成  31254  -49.0  17260   6864  10396   5278  1694  3495    89   78

      11   12    13     14    15    16     17
0    652  159   859   6883  -6.0   348  -88.0
1    432   68   741   4524  -2.0   147  -57.0
2    556   83   451   3877  -1.0  1604 -922.0
3   1181  307   521   4190  -3.0   132   -3.0
4    651  178   964   6061  -2.0   210  -79.0
5    560  268   599   5312 -11.0   459 -127.0
6    967  971   709   5330  -1.0   288  -76.0
7    797  349   557   5606  -1.0   202  -25.0
8    173   31   479   3338  -3.0   133  -47.0
9    832  202   407   4565  -1.0   267  -42.0
10  1279  407   785   5954  -3.0   386  -73.0
11   815   37  1473   9184  -2.0   258  -69.0
12  1177  209  1817  10287  -3.0   181  -72.0
13   446   58   577   5015  -3.0   382 -103.0
14   690  107   940  10170  -2.0   560 -117.0
15   358   40   824   5397  -2.0    93  -22.0
16  1240  220  1493   8465  -1.0   324  -78.0
17   836  166   830   6666  -1.0   286  -72.0
18   305   19   722   4475  -1.0    84   -8.0
19  2119  946   855   8227  -4.0   319 -144.0
20   506  454  1079   8838  -1.0    83   -7.0
21  1026  123  1080   9716  -4.0   614 -309.0
22  1323   98  1405  16355  -1.0   506 -105.0
23   892  104   660   6785 -29.0   197  -20.0

/Users/H/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [187]:
df14 = make_sheet(df, 'H14')

In [189]:
df14[0]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45
10,NaN,平成９,NaN,年,NaN,945839,-2591.0,NaN,549522,NaN,NaN,186374,NaN,NaN,363148,NaN,NaN,180320,NaN,NaN,43376,NaN,NaN,132292,NaN,4652,NaN,NaN,2835,NaN,18416,NaN,NaN,5833,NaN,NaN,20384,NaN,NaN,160238,-90.0,NaN,8291,-2501.0,NaN,９
11,NaN,NaN,10,年,NaN,931917,-2633.0,NaN,548197,NaN,NaN,195662,NaN,NaN,352535,NaN,NaN,169856,NaN,NaN,41913,NaN,NaN,123384,NaN,4559,NaN,NaN,2740,NaN,19033,NaN,NaN,5791,NaN,NaN,20222,NaN,NaN,157838,-91.0,NaN,8240,-2542.0,NaN,10
12,NaN,NaN,11,年,NaN,921544,-2748.0,NaN,543083,NaN,NaN,203759,NaN,NaN,339324,NaN,NaN,163018,NaN,NaN,39669,NaN,NaN,118858,NaN,4491,NaN,NaN,2683,NaN,19295,NaN,NaN,5711,NaN,NaN,20154,NaN,NaN,159341,-95.0,NaN,8259,-2653.0,NaN,11
13,NaN,NaN,12,年,NaN,917210,-2789.0,NaN,539770,NaN,NaN,210901,NaN,NaN,328869,NaN,NaN,158380,NaN,NaN,39142,NaN,NaN,114631,NaN,4607,NaN,NaN,2637,NaN,19560,NaN,NaN,5669,NaN,NaN,20426,NaN,NaN,162574,-101.0,NaN,8194,-2688.0,NaN,12
14,NaN,NaN,13,年,NaN,913052,-2753.0,NaN,537677,NaN,NaN,216334,NaN,NaN,321343,NaN,NaN,153369,NaN,NaN,38250,NaN,NaN,110497,NaN,4622,NaN,NaN,2479,NaN,19813,NaN,NaN,5604,NaN,NaN,20827,NaN,NaN,165220,-88.0,NaN,8063,-2665.0,NaN,13

In [174]:
df17[0].isnull().iloc[3, 36]

False

In [193]:
df14[0]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45
10,NaN,平成９,NaN,年,NaN,945839,-2591.0,NaN,549522,NaN,NaN,186374,NaN,NaN,363148,NaN,NaN,180320,NaN,NaN,43376,NaN,NaN,132292,NaN,4652,NaN,NaN,2835,NaN,18416,NaN,NaN,5833,NaN,NaN,20384,NaN,NaN,160238,-90.0,NaN,8291,-2501.0,NaN,９
11,NaN,10,10,年,NaN,931917,-2633.0,NaN,548197,NaN,NaN,195662,NaN,NaN,352535,NaN,NaN,169856,NaN,NaN,41913,NaN,NaN,123384,NaN,4559,NaN,NaN,2740,NaN,19033,NaN,NaN,5791,NaN,NaN,20222,NaN,NaN,157838,-91.0,NaN,8240,-2542.0,NaN,10
12,NaN,11,11,年,NaN,921544,-2748.0,NaN,543083,NaN,NaN,203759,NaN,NaN,339324,NaN,NaN,163018,NaN,NaN,39669,NaN,NaN,118858,NaN,4491,NaN,NaN,2683,NaN,19295,NaN,NaN,5711,NaN,NaN,20154,NaN,NaN,159341,-95.0,NaN,8259,-2653.0,NaN,11
13,NaN,12,12,年,NaN,917210,-2789.0,NaN,539770,NaN,NaN,210901,NaN,NaN,328869,NaN,NaN,158380,NaN,NaN,39142,NaN,NaN,114631,NaN,4607,NaN,NaN,2637,NaN,19560,NaN,NaN,5669,NaN,NaN,20426,NaN,NaN,162574,-101.0,NaN,8194,-2688.0,NaN,12
14,NaN,13,13,年,NaN,913052,-2753.0,NaN,537677,NaN,NaN,216334,NaN,NaN,321343,NaN,NaN,153369,NaN,NaN,38250,NaN,NaN,110497,NaN,4622,NaN,NaN,2479,NaN,19813,NaN,NaN,5604,NaN,NaN,20827,NaN,NaN,165220,-88.0,NaN,8063,-2665.0,NaN,13